// limztudio@gmail.com
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


#include "module.h"

#include <core/common/log.h>


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


NWB_TEX_CONV_BEGIN


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


namespace __hidden_output{


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


inline constexpr AStringView s_NewLine = "\r\n";


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


void RemoveTemporaryFile(const Path& path){
    ErrorCode errorCode;
    if(!RemoveFile(path, errorCode)){
        if(errorCode){
            NWB_LOGGER_CRITICAL_WARNING(NWB_TEXT("tex_conv: failed to remove temporary output '{}': {}")
                , PathToString<tchar>(path)
                , StringConvert(errorCode.message())
            );
        }
    }
}

bool CheckOutputPath(const Path& path, const bool force, const bool temporary){
    ErrorCode errorCode;
    const bool exists = FileExists(path, errorCode);
    if(errorCode){
        NWB_LOGGER_ERROR(NWB_TEXT("tex_conv: failed to query output path '{}': {}")
            , PathToString<tchar>(path)
            , StringConvert(errorCode.message())
        );
        return false;
    }
    if(!exists)
        return true;

    const bool directory = IsDirectory(path, errorCode);
    if(errorCode){
        NWB_LOGGER_ERROR(NWB_TEXT("tex_conv: failed to inspect output path '{}': {}")
            , PathToString<tchar>(path)
            , StringConvert(errorCode.message())
        );
        return false;
    }
    if(directory){
        NWB_LOGGER_ERROR(NWB_TEXT("tex_conv: output path is a directory: '{}'"), PathToString<tchar>(path));
        return false;
    }
    if(temporary){
        NWB_LOGGER_ERROR(NWB_TEXT("tex_conv: temporary output already exists: '{}'"), PathToString<tchar>(path));
        return false;
    }
    if(!force){
        NWB_LOGGER_ERROR(NWB_TEXT("tex_conv: Output already exists: '{}'. Pass --force to replace both output files.")
            , PathToString<tchar>(path)
        );
        return false;
    }

    return true;
}

bool RemoveOutputPath(const Path& path){
    ErrorCode errorCode;
    const bool removed = RemoveFile(path, errorCode);
    if(errorCode){
        NWB_LOGGER_ERROR(NWB_TEXT("tex_conv: failed to replace output '{}': {}")
            , PathToString<tchar>(path)
            , StringConvert(errorCode.message())
        );
        return false;
    }
    if(removed)
        return true;

    const bool exists = FileExists(path, errorCode);
    if(errorCode){
        NWB_LOGGER_ERROR(NWB_TEXT("tex_conv: failed to query output '{}': {}")
            , PathToString<tchar>(path)
            , StringConvert(errorCode.message())
        );
        return false;
    }
    if(!exists)
        return true;

    NWB_LOGGER_ERROR(NWB_TEXT("tex_conv: failed to remove existing output '{}'."), PathToString<tchar>(path));
    return false;
}

AString BuildMetadata(const TexturePayload& payload, const Path& dataPath){
    AStringStream output;
    const AString dataName = MakeJsonEscapedText<AString>(PathToGenericString<AString>(dataPath.filename()));
    const bool hdr = payload.format == TexturePayloadFormat::UastcHdr4x4;
    const AStringView formatName = hdr ? s_UastcHdr4x4Format : s_UastcLdr4x4Format;
    const u32 metadataVersion = hdr ? s_UastcHdrTextureMetadataVersion : s_UastcLdrTextureMetadataVersion;
    if(
        (!hdr && (!payload.alphaBytes.empty() || payload.alphaMode == TextureAlphaMode::SeparateUastcLdr4x4))
        || (hdr && payload.srgb)
        || (hdr && payload.hasAlpha != (payload.alphaMode != TextureAlphaMode::Opaque))
        || (hdr && payload.alphaMode == TextureAlphaMode::EmbeddedLdr)
        || (hdr && payload.alphaMode == TextureAlphaMode::SeparateUastcLdr4x4 && payload.alphaBytes.size() != payload.bytes.size())
        || (hdr && payload.alphaMode != TextureAlphaMode::SeparateUastcLdr4x4 && !payload.alphaBytes.empty())
        || (hdr && payload.alphaMode != TextureAlphaMode::ConstantUnorm8 && payload.alphaConstantUnorm8 != s_OpaqueAlphaUnorm8)
    )
        return {};
    u32 blockWidth = 0u;
    u32 blockHeight = 0u;
    u32 bytesPerBlock = 0u;
    if(!GetTexturePayloadBlockLayout(payload.format, blockWidth, blockHeight, bytesPerBlock))
        return {};
    const AStringView dimensionName = payload.dimension == TextureDimension::TextureCube
        ? s_TextureCubeDimension
        : payload.dimension == TextureDimension::Texture3D
            ? s_Texture3DDimension
            : s_Texture2DDimension
    ;
    output
        << "// Generated by tex_conv. The referenced .tex file is a contiguous raw "
        << (hdr ? "UASTC HDR RGB block stream, optionally followed by a matched UASTC LDR alpha stream." : "UASTC LDR block stream.") << s_NewLine
        << "texture asset;" << s_NewLine
        << s_NewLine
        << "asset.version = " << metadataVersion << ";" << s_NewLine
        << "asset.format = \"" << formatName << "\";" << s_NewLine
    ;
    if(!hdr)
        output << "asset.uastc_spec_revision = \"" << s_UastcSpecificationRevision << "\";" << s_NewLine;
    else
        output << "asset.uastc_hdr_spec_revision = \"" << s_UastcSpecificationRevision << "\";" << s_NewLine;
    output
        << "asset.color_space = \"" << (payload.srgb ? s_SrgbColorSpace : s_LinearColorSpace) << "\";" << s_NewLine
        << "asset.dimension = \"" << dimensionName << "\";" << s_NewLine
        << "asset.depth = " << payload.depth << ";" << s_NewLine
    ;
    output
        << "asset.width = " << payload.width << ";" << s_NewLine
        << "asset.height = " << payload.height << ";" << s_NewLine
        << "asset.block_width = " << blockWidth << ";" << s_NewLine
        << "asset.block_height = " << blockHeight << ";" << s_NewLine
        << "asset.bytes_per_block = " << bytesPerBlock << ";" << s_NewLine
        << "asset.payload_layout = \"" << s_MipMajorSliceMajorBlocksPayloadLayout << "\";" << s_NewLine
        << "asset.mip_address_mode = \"" << s_ClampMipAddressMode << "\";" << s_NewLine
        << "asset.has_alpha = " << (payload.hasAlpha ? 1 : 0) << ";" << s_NewLine
    ;
    if(hdr){
        switch(payload.alphaMode){
        case TextureAlphaMode::Opaque:
            output << "asset.alpha_mode = \"" << s_AlphaOpaqueMode << "\";" << s_NewLine;
            break;
        case TextureAlphaMode::ConstantUnorm8:
            output
                << "asset.alpha_mode = \"" << s_AlphaConstantUnorm8Mode << "\";" << s_NewLine
                << "asset.alpha_constant_unorm8 = " << static_cast<u32>(payload.alphaConstantUnorm8) << ";" << s_NewLine
            ;
            break;
        case TextureAlphaMode::SeparateUastcLdr4x4:
            output
                << "asset.alpha_mode = \"" << s_AlphaUastcLdr4x4Mode << "\";" << s_NewLine
                << "asset.alpha_payload_offset_bytes = " << payload.bytes.size() << ";" << s_NewLine
                << "asset.alpha_payload_byte_count = " << payload.alphaBytes.size() << ";" << s_NewLine
                << "asset.alpha_uastc_spec_revision = \"" << s_UastcSpecificationRevision << "\";" << s_NewLine
            ;
            break;
        default:
            return {};
        }
    }
    output
        << "asset.mip_count = " << payload.mips.size() << ";" << s_NewLine
        << "asset.data = \"" << dataName << "\";" << s_NewLine
        << "asset.mips = [" << s_NewLine
    ;

    for(usize index = 0u; index < payload.mips.size(); ++index){
        const MipLevel& mip = payload.mips[index];
        output
            << "    { \"level\": " << mip.level
            << ", \"width\": " << mip.width
            << ", \"height\": " << mip.height
            << ", \"blocks_x\": " << mip.blocksX
            << ", \"blocks_y\": " << mip.blocksY
            << ", \"offset_bytes\": " << mip.offsetBytes
            << ", \"size_bytes\": " << mip.sizeBytes
            << ", \"slices\": " << mip.sliceCount
        ;
        output
            << " }" << (index + 1u == payload.mips.size() ? "" : ",") << s_NewLine
        ;
    }

    output << "];" << s_NewLine;
    return output.str();
}

bool WriteTexturePayloadPart(OutputFileStream& stream, const Vector<u8>& bytes){
    if(!GlobalFilesystemDetail::CanRepresentStreamSize(static_cast<u64>(bytes.size())))
        return false;
    if(bytes.empty())
        return true;

    stream.write(
        reinterpret_cast<const char*>(bytes.data()),
        static_cast<StreamSize>(bytes.size())
    );
    return stream.good();
}

bool WriteTexturePayload(const Path& path, const TexturePayload& payload){
    OutputFileStream stream(path, s_FileOpenBinary | s_FileOpenTruncate);
    if(!stream.is_open())
        return false;

    return
        WriteTexturePayloadPart(stream, payload.bytes)
        && WriteTexturePayloadPart(stream, payload.alphaBytes)
    ;
}


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


};


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


bool ResolveOutputPaths(const Path& inputPath, const AString& outputArgument, OutputPaths& outOutputPaths){
    if(outputArgument.empty()){
        outOutputPaths.metadata = inputPath;
        outOutputPaths.metadata.replace_extension(".nwb");
    }
    else{
        const Path outputBase(UtilityDetail::Arena(), outputArgument);
        const AString extension = ToAsciiLowerCopy(PathToGenericString<AString>(outputBase.extension()));
        if(extension.empty())
            outOutputPaths.metadata = outputBase;
        else if(extension == ".nwb")
            outOutputPaths.metadata = outputBase;
        else{
            NWB_LOGGER_ERROR(NWB_TEXT("tex_conv: --output must be an output base name or a .nwb filename."));
            return false;
        }
        outOutputPaths.metadata.replace_extension(".nwb");
    }

    outOutputPaths.data = outOutputPaths.metadata;
    outOutputPaths.data.replace_extension(".tex");
    outOutputPaths.metadataTemporary = outOutputPaths.metadata;
    outOutputPaths.metadataTemporary += ".tmp";
    outOutputPaths.dataTemporary = outOutputPaths.data;
    outOutputPaths.dataTemporary += ".tmp";
    return true;
}

bool ValidateOutputPaths(const OutputPaths& outputPaths, const bool force){
    return __hidden_output::CheckOutputPath(outputPaths.metadata, force, false)
        && __hidden_output::CheckOutputPath(outputPaths.data, force, false)
        && __hidden_output::CheckOutputPath(outputPaths.metadataTemporary, false, true)
        && __hidden_output::CheckOutputPath(outputPaths.dataTemporary, false, true)
    ;
}

bool WriteOutputs(const OutputPaths& outputPaths, const TexturePayload& payload, const bool force){
    const AString metadata = __hidden_output::BuildMetadata(payload, outputPaths.data);
    if(metadata.empty()){
        NWB_LOGGER_ERROR(NWB_TEXT("tex_conv: cannot write an unsupported texture payload format."));
        return false;
    }
    if(payload.alphaBytes.size() > Limit<usize>::s_Max - payload.bytes.size()){
        NWB_LOGGER_ERROR(NWB_TEXT("tex_conv: texture payload is too large to write."));
        return false;
    }
    if(!__hidden_output::WriteTexturePayload(outputPaths.dataTemporary, payload)){
        NWB_LOGGER_ERROR(NWB_TEXT("tex_conv: failed to write output data file '{}'.")
            , PathToString<tchar>(outputPaths.dataTemporary)
        );
        __hidden_output::RemoveTemporaryFile(outputPaths.dataTemporary);
        return false;
    }
    if(!WriteTextFile(outputPaths.metadataTemporary, metadata)){
        NWB_LOGGER_ERROR(NWB_TEXT("tex_conv: failed to write output metadata file '{}'.")
            , PathToString<tchar>(outputPaths.metadataTemporary)
        );
        __hidden_output::RemoveTemporaryFile(outputPaths.dataTemporary);
        __hidden_output::RemoveTemporaryFile(outputPaths.metadataTemporary);
        return false;
    }

    if(force){
        if(!__hidden_output::RemoveOutputPath(outputPaths.data) || !__hidden_output::RemoveOutputPath(outputPaths.metadata)){
            __hidden_output::RemoveTemporaryFile(outputPaths.dataTemporary);
            __hidden_output::RemoveTemporaryFile(outputPaths.metadataTemporary);
            return false;
        }
    }

    ErrorCode errorCode;
    if(!RenamePath(outputPaths.dataTemporary, outputPaths.data, errorCode)){
        NWB_LOGGER_ERROR(
            NWB_TEXT("tex_conv: failed to finalize output data file '{}': {}")
            , PathToString<tchar>(outputPaths.data)
            , StringConvert(errorCode.message())
        );
        __hidden_output::RemoveTemporaryFile(outputPaths.dataTemporary);
        __hidden_output::RemoveTemporaryFile(outputPaths.metadataTemporary);
        return false;
    }
    if(!RenamePath(outputPaths.metadataTemporary, outputPaths.metadata, errorCode)){
        NWB_LOGGER_ERROR(
            NWB_TEXT("tex_conv: failed to finalize output metadata file '{}': {}")
            , PathToString<tchar>(outputPaths.metadata)
            , StringConvert(errorCode.message())
        );
        __hidden_output::RemoveTemporaryFile(outputPaths.data);
        __hidden_output::RemoveTemporaryFile(outputPaths.metadataTemporary);
        return false;
    }

    return true;
}


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


NWB_TEX_CONV_END


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

