// limztudio@gmail.com
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


#include "module.h"

#include <core/common/log.h>


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


NWB_TEX_CONV_BEGIN


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


namespace __hidden_output{


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


inline constexpr AStringView s_NewLine = "\r\n";


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


void RemoveTemporaryFile(const Path& path){
    ErrorCode errorCode;
    if(!RemoveFile(path, errorCode)){
        if(errorCode){
            NWB_LOGGER_WARNING(NWB_TEXT("tex_conv: failed to remove temporary output '{}': {}")
                , PathToString<tchar>(path)
                , StringConvert(errorCode.message())
            );
        }
    }
}

bool CheckOutputPath(const Path& path, const bool force, const bool temporary){
    ErrorCode errorCode;
    const bool exists = FileExists(path, errorCode);
    if(errorCode){
        NWB_LOGGER_WARNING(NWB_TEXT("tex_conv: failed to query output path '{}': {}")
            , PathToString<tchar>(path)
            , StringConvert(errorCode.message())
        );
        return false;
    }
    if(!exists)
        return true;

    const bool directory = IsDirectory(path, errorCode);
    if(errorCode){
        NWB_LOGGER_WARNING(NWB_TEXT("tex_conv: failed to inspect output path '{}': {}")
            , PathToString<tchar>(path)
            , StringConvert(errorCode.message())
        );
        return false;
    }
    if(directory){
        NWB_LOGGER_WARNING(NWB_TEXT("tex_conv: output path is a directory: '{}'"), PathToString<tchar>(path));
        return false;
    }
    if(temporary){
        NWB_LOGGER_WARNING(NWB_TEXT("tex_conv: temporary output already exists: '{}'"), PathToString<tchar>(path));
        return false;
    }
    if(!force){
        NWB_LOGGER_WARNING(NWB_TEXT("tex_conv: Output already exists: '{}'. Pass --force to replace both output files.")
            , PathToString<tchar>(path)
        );
        return false;
    }

    return true;
}

bool RemoveOutputPath(const Path& path){
    ErrorCode errorCode;
    const bool removed = RemoveFile(path, errorCode);
    if(errorCode){
        NWB_LOGGER_WARNING(NWB_TEXT("tex_conv: failed to replace output '{}': {}")
            , PathToString<tchar>(path)
            , StringConvert(errorCode.message())
        );
        return false;
    }
    if(removed)
        return true;

    const bool exists = FileExists(path, errorCode);
    if(errorCode){
        NWB_LOGGER_WARNING(NWB_TEXT("tex_conv: failed to query output '{}': {}")
            , PathToString<tchar>(path)
            , StringConvert(errorCode.message())
        );
        return false;
    }
    if(!exists)
        return true;

    NWB_LOGGER_WARNING(NWB_TEXT("tex_conv: failed to remove existing output '{}'."), PathToString<tchar>(path));
    return false;
}

AString BuildMetadata(const TexturePayload& payload, const Path& dataPath, const bool srgb){
    AStringStream output;
    const AString dataName = MakeJsonEscapedText<AString>(PathToUtf8(dataPath.filename()));
    output
        << "// Generated by tex_conv. The referenced .tex file is a contiguous raw UASTC block stream." << s_NewLine
        << "texture asset;" << s_NewLine
        << s_NewLine
        << "asset.version = 1;" << s_NewLine
        << "asset.format = \"uastc_ldr_4x4\";" << s_NewLine
        << "asset.uastc_spec_revision = \"" << s_UastcSpecificationRevision << "\";" << s_NewLine
        << "asset.color_space = \"" << (srgb ? "srgb" : "linear") << "\";" << s_NewLine
        << "asset.width = " << payload.width << ";" << s_NewLine
        << "asset.height = " << payload.height << ";" << s_NewLine
        << "asset.block_width = " << s_UastcBlockWidth << ";" << s_NewLine
        << "asset.block_height = " << s_UastcBlockHeight << ";" << s_NewLine
        << "asset.bytes_per_block = " << s_UastcBytesPerBlock << ";" << s_NewLine
        << "asset.payload_layout = \"mip_major_blocks\";" << s_NewLine
        << "asset.mip_address_mode = \"clamp\";" << s_NewLine
        << "asset.has_alpha = " << (payload.hasAlpha ? 1 : 0) << ";" << s_NewLine
        << "asset.mip_count = " << payload.mips.size() << ";" << s_NewLine
        << "asset.data = \"" << dataName << "\";" << s_NewLine
        << "asset.mips = [" << s_NewLine
    ;

    for(usize index = 0u; index < payload.mips.size(); ++index){
        const MipLevel& mip = payload.mips[index];
        output
            << "    { \"level\": " << mip.level
            << ", \"width\": " << mip.width
            << ", \"height\": " << mip.height
            << ", \"blocks_x\": " << mip.blocksX
            << ", \"blocks_y\": " << mip.blocksY
            << ", \"offset_bytes\": " << mip.offsetBytes
            << ", \"size_bytes\": " << mip.sizeBytes
            << " }" << (index + 1u == payload.mips.size() ? "" : ",") << s_NewLine
        ;
    }

    output << "];" << s_NewLine;
    return output.str();
}


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


};


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


bool ResolveOutputPaths(const Path& inputPath, const AString& outputArgument, OutputPaths& outOutputPaths){
    if(outputArgument.empty()){
        outOutputPaths.metadata = inputPath;
        outOutputPaths.metadata.replace_extension(".nwb");
    }
    else{
        const Path outputBase = PathFromUtf8(outputArgument);
        const AString extension = ToAsciiLowerCopy(PathToUtf8(outputBase.extension()));
        if(extension.empty())
            outOutputPaths.metadata = outputBase;
        else if(extension == ".nwb")
            outOutputPaths.metadata = outputBase;
        else{
            NWB_LOGGER_WARNING(NWB_TEXT("tex_conv: --output must be an output base name or a .nwb filename."));
            return false;
        }
        outOutputPaths.metadata.replace_extension(".nwb");
    }

    outOutputPaths.data = outOutputPaths.metadata;
    outOutputPaths.data.replace_extension(".tex");
    outOutputPaths.metadataTemporary = outOutputPaths.metadata;
    outOutputPaths.metadataTemporary += ".tmp";
    outOutputPaths.dataTemporary = outOutputPaths.data;
    outOutputPaths.dataTemporary += ".tmp";
    return true;
}

bool ValidateOutputPaths(const OutputPaths& outputPaths, const bool force){
    return __hidden_output::CheckOutputPath(outputPaths.metadata, force, false)
        && __hidden_output::CheckOutputPath(outputPaths.data, force, false)
        && __hidden_output::CheckOutputPath(outputPaths.metadataTemporary, false, true)
        && __hidden_output::CheckOutputPath(outputPaths.dataTemporary, false, true)
    ;
}

bool WriteOutputs(const OutputPaths& outputPaths, const TexturePayload& payload, const bool srgb, const bool force){
    const AString metadata = __hidden_output::BuildMetadata(payload, outputPaths.data, srgb);
    if(!WriteBinaryFile(outputPaths.dataTemporary, payload.bytes)){
        NWB_LOGGER_WARNING(NWB_TEXT("tex_conv: failed to write output data file '{}'.")
            , PathToString<tchar>(outputPaths.dataTemporary)
        );
        __hidden_output::RemoveTemporaryFile(outputPaths.dataTemporary);
        return false;
    }
    if(!WriteTextFile(outputPaths.metadataTemporary, metadata)){
        NWB_LOGGER_WARNING(NWB_TEXT("tex_conv: failed to write output metadata file '{}'.")
            , PathToString<tchar>(outputPaths.metadataTemporary)
        );
        __hidden_output::RemoveTemporaryFile(outputPaths.dataTemporary);
        __hidden_output::RemoveTemporaryFile(outputPaths.metadataTemporary);
        return false;
    }

    if(force){
        if(!__hidden_output::RemoveOutputPath(outputPaths.data) || !__hidden_output::RemoveOutputPath(outputPaths.metadata)){
            __hidden_output::RemoveTemporaryFile(outputPaths.dataTemporary);
            __hidden_output::RemoveTemporaryFile(outputPaths.metadataTemporary);
            return false;
        }
    }

    ErrorCode errorCode;
    if(!RenamePath(outputPaths.dataTemporary, outputPaths.data, errorCode)){
        NWB_LOGGER_WARNING(
            NWB_TEXT("tex_conv: failed to finalize output data file '{}': {}")
            , PathToString<tchar>(outputPaths.data)
            , StringConvert(errorCode.message())
        );
        __hidden_output::RemoveTemporaryFile(outputPaths.dataTemporary);
        __hidden_output::RemoveTemporaryFile(outputPaths.metadataTemporary);
        return false;
    }
    if(!RenamePath(outputPaths.metadataTemporary, outputPaths.metadata, errorCode)){
        NWB_LOGGER_WARNING(
            NWB_TEXT("tex_conv: failed to finalize output metadata file '{}': {}")
            , PathToString<tchar>(outputPaths.metadata)
            , StringConvert(errorCode.message())
        );
        __hidden_output::RemoveTemporaryFile(outputPaths.data);
        __hidden_output::RemoveTemporaryFile(outputPaths.metadataTemporary);
        return false;
    }

    return true;
}


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


NWB_TEX_CONV_END


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

