// limztudio@gmail.com
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


#include "module.h"

#include <core/common/log.h>

#include <global/blocking_io.h>
#include <global/scope_exit.h>

#if !defined(NWB_PLATFORM_WINDOWS)
#include <fcntl.h>
#endif


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


NWB_TEX_CONV_BEGIN


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


namespace __hidden_output{


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


inline constexpr AStringView s_NewLine = "\r\n";
inline constexpr AStringView s_NwbOutputExtension = ".nwb";


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


bool CheckOutputPath(const Path& path, const bool force, const bool temporary){
    ErrorCode errorCode;
    const bool exists = FileExistsNoFollow(path, errorCode);
    if(errorCode){
        NWB_LOGGER_ERROR(NWB_TEXT("tex_conv: failed to query output path '{}': {}")
            , PathToString<tchar>(path)
            , StringConvert(errorCode.message())
        );
        return false;
    }
    if(!exists)
        return true;

    const bool regular = IsRegularFile(path, errorCode);
    if(errorCode){
        NWB_LOGGER_ERROR(NWB_TEXT("tex_conv: failed to inspect output path '{}': {}")
            , PathToString<tchar>(path)
            , StringConvert(errorCode.message())
        );
        return false;
    }
    if(!regular){
        NWB_LOGGER_ERROR(NWB_TEXT("tex_conv: output path is not a regular file: '{}'"), PathToString<tchar>(path));
        return false;
    }
    if(temporary){
        NWB_LOGGER_ERROR(NWB_TEXT("tex_conv: publication work path already exists: '{}'"), PathToString<tchar>(path));
        return false;
    }
    if(!force){
        NWB_LOGGER_ERROR(NWB_TEXT("tex_conv: Output already exists: '{}'. Pass --force to replace both output files.")
            , PathToString<tchar>(path)
        );
        return false;
    }

    return true;
}

AString BuildMetadata(const TexturePayload& payload, const Path& dataPath){
    AStringStream output;
    const AString dataName = MakeJsonEscapedText<AString>(PathToGenericString<AString>(dataPath.filename()));
    const bool hdr = payload.format == TexturePayloadFormat::UastcHdr4x4;
    const AStringView formatName = hdr ? TextureFormat::s_UastcHdr4x4Format : TextureFormat::s_UastcLdr4x4Format;
    if(
        (payload.format != TexturePayloadFormat::UastcLdr4x4 && payload.format != TexturePayloadFormat::UastcHdr4x4)
        || (!hdr && (!payload.alphaBytes.empty() || payload.alphaMode == TextureAlphaMode::SeparateUastcLdr4x4))
        || (hdr && payload.srgb)
        || (hdr && payload.hasAlpha != (payload.alphaMode != TextureAlphaMode::Opaque))
        || (hdr && payload.alphaMode == TextureAlphaMode::EmbeddedLdr)
        || (hdr && payload.alphaMode == TextureAlphaMode::SeparateUastcLdr4x4 && payload.alphaBytes.size() != payload.bytes.size())
        || (hdr && payload.alphaMode != TextureAlphaMode::SeparateUastcLdr4x4 && !payload.alphaBytes.empty())
        || (hdr && payload.alphaMode != TextureAlphaMode::ConstantUnorm8 && payload.alphaConstantUnorm8 != TextureFormat::s_OpaqueAlphaUnorm8)
    )
        return {};
    const AStringView dimensionName = payload.dimension == TextureDimension::TextureCube
        ? TextureFormat::s_TextureCubeDimension
        : payload.dimension == TextureDimension::Texture3D
            ? TextureFormat::s_Texture3DDimension
            : TextureFormat::s_Texture2DDimension
    ;
    output
        << "// Generated by tex_conv. The referenced .tex file is a contiguous raw "
        << (hdr ? "UASTC HDR RGB block stream, optionally followed by a matched UASTC LDR alpha stream." : "UASTC LDR block stream.") << s_NewLine
        << "texture asset;" << s_NewLine
        << s_NewLine
        << "asset.format = \"" << formatName << "\";" << s_NewLine
    ;
    if(!hdr)
        output << "asset.color_space = \"" << (payload.srgb ? TextureFormat::s_SrgbColorSpace : TextureFormat::s_LinearColorSpace) << "\";" << s_NewLine;
    output << "asset.dimension = \"" << dimensionName << "\";" << s_NewLine;
    if(payload.dimension == TextureDimension::Texture3D)
        output << "asset.depth = " << payload.depth << ";" << s_NewLine;
    output
        << "asset.width = " << payload.width << ";" << s_NewLine
        << "asset.height = " << payload.height << ";" << s_NewLine
    ;
    if(!hdr)
        output << "asset.has_alpha = " << (payload.hasAlpha ? 1 : 0) << ";" << s_NewLine;
    else{
        switch(payload.alphaMode){
        case TextureAlphaMode::Opaque:
            output << "asset.alpha_mode = \"" << TextureFormat::s_AlphaOpaqueMode << "\";" << s_NewLine;
            break;
        case TextureAlphaMode::ConstantUnorm8:
            output
                << "asset.alpha_mode = \"" << TextureFormat::s_AlphaConstantUnorm8Mode << "\";" << s_NewLine
                << "asset.alpha_constant_unorm8 = " << static_cast<u32>(payload.alphaConstantUnorm8) << ";" << s_NewLine
            ;
            break;
        case TextureAlphaMode::SeparateUastcLdr4x4:
            output << "asset.alpha_mode = \"" << TextureFormat::s_AlphaUastcLdr4x4Mode << "\";" << s_NewLine;
            break;
        default:
            return {};
        }
    }
    output << "asset.data = \"" << dataName << "\";" << s_NewLine;
    return output.str();
}

[[nodiscard]] bool StageOutput(
    const Path& path,
    const void* const data,
    const usize count,
    const void* const tail,
    const usize tailCount,
    bool& outOwned)noexcept{
#if defined(NWB_PLATFORM_WINDOWS)
    const HANDLE handle = CreateFile(path.c_str(), GENERIC_WRITE, 0u, nullptr, CREATE_NEW, FILE_ATTRIBUTE_NORMAL, nullptr);
    if(handle == INVALID_HANDLE_VALUE)
        return false;
    outOwned = true;
    const bool written = WriteAllWin32Handle(handle, data, count) && WriteAllWin32Handle(handle, tail, tailCount);
    const bool flushed = written && FlushFileBuffers(handle);
    const bool closed = CloseHandle(handle);
#else
    const int descriptor = open(path.c_str(), O_WRONLY | O_CREAT | O_EXCL | O_CLOEXEC, 0666u);
    if(descriptor < 0)
        return false;
    outOwned = true;
    const bool written = WriteAllFileDescriptor(descriptor, data, count) && WriteAllFileDescriptor(descriptor, tail, tailCount);
    const bool flushed = written && fsync(descriptor) == 0;
    const bool closed = close(descriptor) == 0;
#endif
    return written && flushed && closed;
}

void CaptureCleanupFailure(const Path& path, const ErrorCode& error)noexcept{
    const DiagnosticEventText diagnostic = MakeDiagnosticEventText(
        "tex_conv: publication cleanup failed for '{}', error {}",
        path.c_str(),
        error.value()
    );
    CaptureDiagnosticEvent("tex_conv_publication", diagnostic.view(), __FILE__, __LINE__);
}


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


};


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


bool ResolveOutputPaths(const Path& inputPath, const AStringView outputArgument, OutputPaths& outOutputPaths){
    if(outputArgument.empty()){
        outOutputPaths.metadata = inputPath;
        outOutputPaths.metadata.replaceExtension(__hidden_output::s_NwbOutputExtension);
    }
    else{
        const Path outputBase(UtilityDetail::Arena(), outputArgument);
        const AString extension = LowerPathExtension<AString>(outputBase);
        if(extension.empty())
            outOutputPaths.metadata = outputBase;
        else if(extension == __hidden_output::s_NwbOutputExtension)
            outOutputPaths.metadata = outputBase;
        else{
            NWB_LOGGER_ERROR(NWB_TEXT("tex_conv: --output must be an output base name or a .nwb filename."));
            return false;
        }
        outOutputPaths.metadata.replaceExtension(__hidden_output::s_NwbOutputExtension);
    }

    outOutputPaths.data = outOutputPaths.metadata;
    outOutputPaths.data.replaceExtension(TextureFormat::s_TextureDataExtension);
    outOutputPaths.metadataTemporary = outOutputPaths.metadata;
    outOutputPaths.metadataTemporary += s_TemporaryOutputSuffix;
    outOutputPaths.dataTemporary = outOutputPaths.data;
    outOutputPaths.dataTemporary += s_TemporaryOutputSuffix;
    return true;
}

bool ValidateOutputPaths(const OutputPaths& outputPaths, const bool force){
    Path dataBackup(outputPaths.data);
    Path metadataBackup(outputPaths.metadata);
    dataBackup += ".old";
    metadataBackup += ".old";
    return
        __hidden_output::CheckOutputPath(outputPaths.metadata, force, false)
        && __hidden_output::CheckOutputPath(outputPaths.data, force, false)
        && __hidden_output::CheckOutputPath(outputPaths.metadataTemporary, false, true)
        && __hidden_output::CheckOutputPath(outputPaths.dataTemporary, false, true)
        && __hidden_output::CheckOutputPath(dataBackup, false, true)
        && __hidden_output::CheckOutputPath(metadataBackup, false, true)
    ;
}

bool WriteOutputs(const OutputPaths& outputPaths, const TexturePayload& payload, const bool force){
    const AString metadata = __hidden_output::BuildMetadata(payload, outputPaths.data);
    if(metadata.empty()){
        NWB_LOGGER_ERROR(NWB_TEXT("tex_conv: cannot write an unsupported texture payload format."));
        return false;
    }
    if(payload.alphaBytes.size() > Limit<usize>::s_Max - payload.bytes.size()){
        NWB_LOGGER_ERROR(NWB_TEXT("tex_conv: texture payload is too large to write."));
        return false;
    }
    if(!ValidateOutputPaths(outputPaths, force))
        return false;

    Path backups[] = { outputPaths.data, outputPaths.metadata };
    for(Path& backup : backups)
        backup += ".old";
    const Path* outputs[] = { &outputPaths.data, &outputPaths.metadata };
    const Path* temporaries[] = { &outputPaths.dataTemporary, &outputPaths.metadataTemporary };
    bool ownedTemporary[2u] = {};
    bool backedUp[2u] = {};
    bool published[2u] = {};
    ErrorCode removalErrors[2u];
    ErrorCode restorationErrors[2u];
    ErrorCode temporaryErrors[2u];

    // Cleanup never allocates or logs through the throwing logger while an unexpected exception unwinds.
    const auto rollback = [&]()noexcept{
        for(u32 index = 2u; index > 0u; --index){
            const u32 current = index - 1u;
            if(published[current]){
                if(!RemoveFile(*outputs[current], removalErrors[current]) && removalErrors[current])
                    __hidden_output::CaptureCleanupFailure(*outputs[current], removalErrors[current]);
            }
            if(backedUp[current] && !removalErrors[current]){
                if(!RenamePath(backups[current], *outputs[current], restorationErrors[current]))
                    __hidden_output::CaptureCleanupFailure(backups[current], restorationErrors[current]);
            }
            if(ownedTemporary[current]){
                if(!RemoveFile(*temporaries[current], temporaryErrors[current]) && temporaryErrors[current])
                    __hidden_output::CaptureCleanupFailure(*temporaries[current], temporaryErrors[current]);
            }
        }
    };
    ScopeExit restoreOnFailure(rollback);

    const auto publish = [&](){
        if(!__hidden_output::StageOutput(
            outputPaths.dataTemporary,
            payload.bytes.data(),
            payload.bytes.size(),
            payload.alphaBytes.data(),
            payload.alphaBytes.size(),
            ownedTemporary[0u]
        )){
            NWB_LOGGER_ERROR(NWB_TEXT("tex_conv: failed to stage output data file '{}'"), PathToString<tchar>(outputPaths.dataTemporary));
            return false;
        }
        if(!__hidden_output::StageOutput(
            outputPaths.metadataTemporary,
            metadata.data(),
            metadata.size(),
            nullptr,
            0u,
            ownedTemporary[1u]
        )){
            NWB_LOGGER_ERROR(NWB_TEXT("tex_conv: failed to stage output metadata file '{}'"), PathToString<tchar>(outputPaths.metadataTemporary));
            return false;
        }

        for(u32 index = 0u; index < 2u; ++index){
            ErrorCode error;
            const bool present = FileExistsNoFollow(*outputs[index], error);
            if(error){
                NWB_LOGGER_ERROR(NWB_TEXT("tex_conv: failed to inspect existing output '{}'"), PathToString<tchar>(*outputs[index]));
                return false;
            }
            if(!present)
                continue;
            if(!__hidden_output::CheckOutputPath(*outputs[index], force, false))
                return false;
            if(!__hidden_output::CheckOutputPath(backups[index], false, true))
                return false;
            if(!RenamePath(*outputs[index], backups[index], error)){
                NWB_LOGGER_ERROR(NWB_TEXT("tex_conv: failed to preserve existing output '{}': {}")
                    , PathToString<tchar>(*outputs[index])
                    , StringConvert(error.message())
                );
                return false;
            }
            backedUp[index] = true;
        }
        for(u32 index = 0u; index < 2u; ++index){
            ErrorCode error;
            if(!RenamePath(*temporaries[index], *outputs[index], error)){
                NWB_LOGGER_ERROR(NWB_TEXT("tex_conv: failed to finalize output '{}': {}")
                    , PathToString<tchar>(*outputs[index])
                    , StringConvert(error.message())
                );
                return false;
            }
            published[index] = true;
            ownedTemporary[index] = false;
        }
        return true;
    };
    if(!publish()){
        rollback();
        restoreOnFailure.release();
        for(u32 index = 0u; index < 2u; ++index){
            if(backedUp[index] && (removalErrors[index] || restorationErrors[index])){
                NWB_LOGGER_ERROR(NWB_TEXT("tex_conv: failed to restore '{}'; previous output retained at '{}' (remove {}, restore {})")
                    , PathToString<tchar>(*outputs[index])
                    , PathToString<tchar>(backups[index])
                    , removalErrors[index].value()
                    , restorationErrors[index].value()
                );
            }
            if(!backedUp[index] && removalErrors[index]){
                NWB_LOGGER_ERROR(NWB_TEXT("tex_conv: failed to remove newly published output '{}': {}")
                    , PathToString<tchar>(*outputs[index])
                    , StringConvert(removalErrors[index].message())
                );
            }
            if(temporaryErrors[index]){
                NWB_LOGGER_CRITICAL_WARNING(NWB_TEXT("tex_conv: failed to remove unpublished temporary '{}': {}")
                    , PathToString<tchar>(*temporaries[index])
                    , StringConvert(temporaryErrors[index].message())
                );
            }
        }
        return false;
    }

    restoreOnFailure.release();
    for(u32 index = 0u; index < 2u; ++index){
        if(!backedUp[index])
            continue;
        ErrorCode error;
        if(!RemoveFile(backups[index], error) && error){
            NWB_LOGGER_CRITICAL_WARNING(NWB_TEXT("tex_conv: published output pair but could not remove previous backup '{}': {}")
                , PathToString<tchar>(backups[index])
                , StringConvert(error.message())
            );
        }
    }
    return true;
}


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


NWB_TEX_CONV_END


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

