// limztudio@gmail.com
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////



#ifndef NWB_GRAPHICS_CSG_CONSTANTS_H
#define NWB_GRAPHICS_CSG_CONSTANTS_H


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


#undef NWB_CSG_MESHLET_CLASS_UNAFFECTED
#define NWB_CSG_MESHLET_CLASS_UNAFFECTED 0u
#undef NWB_CSG_MESHLET_CLASS_INTERSECTING
#define NWB_CSG_MESHLET_CLASS_INTERSECTING 1u
#undef NWB_CSG_MESHLET_CLASS_FULLY_REMOVED
#define NWB_CSG_MESHLET_CLASS_FULLY_REMOVED 2u

#undef NWB_CSG_BOUNDS_VALID_FLAG
#define NWB_CSG_BOUNDS_VALID_FLAG 1
#undef NWB_CSG_BOUNDS_FINITE_FLAG
#define NWB_CSG_BOUNDS_FINITE_FLAG 2

#undef NWB_CSG_PEEL_LAYER_COUNT
#define NWB_CSG_PEEL_LAYER_COUNT 4u
#undef NWB_CSG_RECEIVER_SURFACE_LAYER_COUNT
#define NWB_CSG_RECEIVER_SURFACE_LAYER_COUNT 8u
#undef NWB_CSG_INTERVAL_PEEL_GROUP_SIZE_X
#define NWB_CSG_INTERVAL_PEEL_GROUP_SIZE_X 8u
#undef NWB_CSG_INTERVAL_PEEL_GROUP_SIZE_Y
#define NWB_CSG_INTERVAL_PEEL_GROUP_SIZE_Y 8u
#undef NWB_CSG_INTERVAL_PEEL_STEP_COUNT
#define NWB_CSG_INTERVAL_PEEL_STEP_COUNT 128u
#undef NWB_CSG_INTERVAL_PEEL_REFINE_STEP_COUNT
#define NWB_CSG_INTERVAL_PEEL_REFINE_STEP_COUNT 6u

#undef NWB_CSG_CAP_NORMAL_IMAGE_FORMAT
#define NWB_CSG_CAP_NORMAL_IMAGE_FORMAT "rgba16f"
#undef NWB_CSG_INTERVAL_DEPTH_IMAGE_FORMAT
#define NWB_CSG_INTERVAL_DEPTH_IMAGE_FORMAT "rg32f"
#undef NWB_CSG_INTERVAL_ID_IMAGE_FORMAT
#define NWB_CSG_INTERVAL_ID_IMAGE_FORMAT "r32ui"
#undef NWB_CSG_RECEIVER_SURFACE_MASK_IMAGE_FORMAT
#define NWB_CSG_RECEIVER_SURFACE_MASK_IMAGE_FORMAT "r32ui"
#undef NWB_CSG_RECEIVER_BACK_SURFACE_MASK_IMAGE_FORMAT
#define NWB_CSG_RECEIVER_BACK_SURFACE_MASK_IMAGE_FORMAT "r32ui"

#undef NWB_CSG_RECEIVER_SURFACE_MASK_RECEIVER_BITS
#define NWB_CSG_RECEIVER_SURFACE_MASK_RECEIVER_BITS 10u
#undef NWB_CSG_RECEIVER_SURFACE_MASK_RECEIVER_MASK
#define NWB_CSG_RECEIVER_SURFACE_MASK_RECEIVER_MASK 0x3ffu
#undef NWB_CSG_RECEIVER_SURFACE_MASK_PAYLOAD_BITS
#define NWB_CSG_RECEIVER_SURFACE_MASK_PAYLOAD_BITS NWB_CSG_RECEIVER_SURFACE_MASK_RECEIVER_BITS
#undef NWB_CSG_RECEIVER_SURFACE_MASK_DEPTH_EPSILON_BITS
#define NWB_CSG_RECEIVER_SURFACE_MASK_DEPTH_EPSILON_BITS 64u
#undef NWB_CSG_RECEIVER_SURFACE_MASK_INVALID
#define NWB_CSG_RECEIVER_SURFACE_MASK_INVALID 0xffffffffu
#undef NWB_CSG_RECEIVER_BACK_SURFACE_MASK_INVALID
#define NWB_CSG_RECEIVER_BACK_SURFACE_MASK_INVALID 0xffffffffu

#if defined(__cplusplus)
#undef NWB_CSG_CAP_NORMAL_CORE_FORMAT
#define NWB_CSG_CAP_NORMAL_CORE_FORMAT NWB::Core::Format::RGBA16_FLOAT
#undef NWB_CSG_INTERVAL_DEPTH_CORE_FORMAT
#define NWB_CSG_INTERVAL_DEPTH_CORE_FORMAT NWB::Core::Format::RG32_FLOAT
#undef NWB_CSG_INTERVAL_ID_CORE_FORMAT
#define NWB_CSG_INTERVAL_ID_CORE_FORMAT NWB::Core::Format::R32_UINT
#undef NWB_CSG_RECEIVER_SURFACE_MASK_CORE_FORMAT
#define NWB_CSG_RECEIVER_SURFACE_MASK_CORE_FORMAT NWB::Core::Format::R32_UINT
#undef NWB_CSG_RECEIVER_BACK_SURFACE_MASK_CORE_FORMAT
#define NWB_CSG_RECEIVER_BACK_SURFACE_MASK_CORE_FORMAT NWB::Core::Format::R32_UINT
#endif

#undef NWB_CSG_INTERVAL_PEEL_PUSH_FRAME_WIDTH
#define NWB_CSG_INTERVAL_PEEL_PUSH_FRAME_WIDTH 0u
#undef NWB_CSG_INTERVAL_PEEL_PUSH_FRAME_HEIGHT
#define NWB_CSG_INTERVAL_PEEL_PUSH_FRAME_HEIGHT 1u
#undef NWB_CSG_INTERVAL_PEEL_PUSH_RECEIVER_COUNT
#define NWB_CSG_INTERVAL_PEEL_PUSH_RECEIVER_COUNT 2u
#undef NWB_CSG_INTERVAL_PEEL_PUSH_LAYER_COUNT
#define NWB_CSG_INTERVAL_PEEL_PUSH_LAYER_COUNT 3u
#undef NWB_CSG_INTERVAL_PEEL_PUSH_CONSTANT_BYTE_SIZE
#define NWB_CSG_INTERVAL_PEEL_PUSH_CONSTANT_BYTE_SIZE 16u


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


#endif
#undef NWB_GRAPHICS_CSG_CONSTANTS_H

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

