// limztudio@gmail.com
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////



#ifndef NWB_GRAPHICS_CSG_CONSTANTS_H
#define NWB_GRAPHICS_CSG_CONSTANTS_H


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


#define NWB_CSG_MESHLET_CLASS_UNAFFECTED 0u
#define NWB_CSG_MESHLET_CLASS_INTERSECTING 1u
#define NWB_CSG_MESHLET_CLASS_FULLY_REMOVED 2u

#define NWB_CSG_BOUNDS_VALID_FLAG 1
#define NWB_CSG_BOUNDS_FINITE_FLAG 2

#define NWB_CSG_PEEL_LAYER_COUNT 4u
#define NWB_CSG_RECEIVER_EVENT_LAYER_COUNT 32u
#define NWB_CSG_RECEIVER_SPAN_LAYER_COUNT 16u
#define NWB_CSG_REMOVED_INTERVAL_LAYER_COUNT 16u
#define NWB_CSG_INTERVAL_PEEL_GROUP_SIZE_X 8u
#define NWB_CSG_INTERVAL_PEEL_GROUP_SIZE_Y 8u

#ifndef NWB_CSG_INTERVAL_PEEL_STEP_COUNT
#define NWB_CSG_INTERVAL_PEEL_STEP_COUNT 128u
#endif
#ifndef NWB_CSG_INTERVAL_PEEL_REFINE_STEP_COUNT
#define NWB_CSG_INTERVAL_PEEL_REFINE_STEP_COUNT 6u
#endif
#ifndef NWB_CSG_RECEIVER_INTERVAL_WORLD_TOLERANCE_SCALE
#define NWB_CSG_RECEIVER_INTERVAL_WORLD_TOLERANCE_SCALE 2.0
#endif
#ifndef NWB_CSG_RECEIVER_INTERVAL_LINEAR_DEPTH_TOLERANCE_SCALE
#define NWB_CSG_RECEIVER_INTERVAL_LINEAR_DEPTH_TOLERANCE_SCALE 2.0
#endif
#ifndef NWB_CSG_RECEIVER_INTERVAL_DISCARD_NEIGHBOR_RADIUS
#define NWB_CSG_RECEIVER_INTERVAL_DISCARD_NEIGHBOR_RADIUS 1
#endif
#ifndef NWB_CSG_REMOVED_INTERVAL_CAP_NEIGHBOR_RADIUS
#define NWB_CSG_REMOVED_INTERVAL_CAP_NEIGHBOR_RADIUS 1
#endif

#define NWB_CSG_CAP_NORMAL_IMAGE_FORMAT "rgba16f"
#define NWB_CSG_INTERVAL_DEPTH_IMAGE_FORMAT "rg32f"
#define NWB_CSG_INTERVAL_LINEAR_DEPTH_IMAGE_FORMAT "rg32f"
#define NWB_CSG_INTERVAL_ID_IMAGE_FORMAT "r32ui"
#define NWB_CSG_RECEIVER_EVENT_DEPTH_IMAGE_FORMAT "r32f"
#define NWB_CSG_RECEIVER_EVENT_DATA_IMAGE_FORMAT "rgba32ui"
#define NWB_CSG_RECEIVER_EVENT_COUNT_IMAGE_FORMAT "r32ui"
#define NWB_CSG_RECEIVER_EVENT_FLAGS_IMAGE_FORMAT "r32ui"
#define NWB_CSG_RECEIVER_SPAN_DEPTH_IMAGE_FORMAT "rg32f"
#define NWB_CSG_RECEIVER_SPAN_DATA_IMAGE_FORMAT "rgba32ui"
#define NWB_CSG_RECEIVER_SPAN_COUNT_IMAGE_FORMAT "r32ui"
#define NWB_CSG_RECEIVER_SPAN_FLAGS_IMAGE_FORMAT "r32ui"
#define NWB_CSG_REMOVED_INTERVAL_DEPTH_IMAGE_FORMAT "rgba32f"
#define NWB_CSG_REMOVED_INTERVAL_CAP_NORMAL_IMAGE_FORMAT "rgba16f"
#define NWB_CSG_REMOVED_INTERVAL_DATA_IMAGE_FORMAT "rgba32ui"
#define NWB_CSG_REMOVED_INTERVAL_COUNT_IMAGE_FORMAT "r32ui"
#define NWB_CSG_REMOVED_INTERVAL_FLAGS_IMAGE_FORMAT "r32ui"

#define NWB_CSG_RECEIVER_INDEX_MASK 0x3ffu
#define NWB_CSG_RECEIVER_EVENT_FACE_BACK 0u
#define NWB_CSG_RECEIVER_EVENT_FACE_FRONT 1u
#define NWB_CSG_RECEIVER_EVENT_OVERFLOW_FLAG 1u
#define NWB_CSG_RECEIVER_SPAN_AMBIGUOUS_FLAG 1u
#define NWB_CSG_RECEIVER_SPAN_OVERFLOW_FLAG 2u
#define NWB_CSG_RECEIVER_SPAN_EVENT_OVERFLOW_FLAG 4u
#define NWB_CSG_REMOVED_INTERVAL_BACK_CAP_VISIBLE_FLAG 1u
#define NWB_CSG_REMOVED_INTERVAL_OVERFLOW_FLAG 2u
#define NWB_CSG_REMOVED_INTERVAL_RECEIVER_SPAN_AMBIGUOUS_FLAG 4u
#define NWB_CSG_REMOVED_INTERVAL_RECEIVER_SPAN_OVERFLOW_FLAG 8u
#define NWB_CSG_REMOVED_INTERVAL_RECEIVER_EVENT_OVERFLOW_FLAG 16u

#if defined(__cplusplus)
#define NWB_CSG_CAP_NORMAL_CORE_FORMAT NWB::Core::Format::RGBA16_FLOAT
#define NWB_CSG_INTERVAL_DEPTH_CORE_FORMAT NWB::Core::Format::RG32_FLOAT
#define NWB_CSG_INTERVAL_LINEAR_DEPTH_CORE_FORMAT NWB::Core::Format::RG32_FLOAT
#define NWB_CSG_INTERVAL_ID_CORE_FORMAT NWB::Core::Format::R32_UINT
#define NWB_CSG_RECEIVER_EVENT_DEPTH_CORE_FORMAT NWB::Core::Format::R32_FLOAT
#define NWB_CSG_RECEIVER_EVENT_DATA_CORE_FORMAT NWB::Core::Format::RGBA32_UINT
#define NWB_CSG_RECEIVER_EVENT_COUNT_CORE_FORMAT NWB::Core::Format::R32_UINT
#define NWB_CSG_RECEIVER_EVENT_FLAGS_CORE_FORMAT NWB::Core::Format::R32_UINT
#define NWB_CSG_RECEIVER_SPAN_DEPTH_CORE_FORMAT NWB::Core::Format::RG32_FLOAT
#define NWB_CSG_RECEIVER_SPAN_DATA_CORE_FORMAT NWB::Core::Format::RGBA32_UINT
#define NWB_CSG_RECEIVER_SPAN_COUNT_CORE_FORMAT NWB::Core::Format::R32_UINT
#define NWB_CSG_RECEIVER_SPAN_FLAGS_CORE_FORMAT NWB::Core::Format::R32_UINT
#define NWB_CSG_REMOVED_INTERVAL_DEPTH_CORE_FORMAT NWB::Core::Format::RGBA32_FLOAT
#define NWB_CSG_REMOVED_INTERVAL_CAP_NORMAL_CORE_FORMAT NWB::Core::Format::RGBA16_FLOAT
#define NWB_CSG_REMOVED_INTERVAL_DATA_CORE_FORMAT NWB::Core::Format::RGBA32_UINT
#define NWB_CSG_REMOVED_INTERVAL_COUNT_CORE_FORMAT NWB::Core::Format::R32_UINT
#define NWB_CSG_REMOVED_INTERVAL_FLAGS_CORE_FORMAT NWB::Core::Format::R32_UINT
#endif

#define NWB_CSG_INTERVAL_DISPATCH_PUSH_FRAME_WIDTH 0u
#define NWB_CSG_INTERVAL_DISPATCH_PUSH_FRAME_HEIGHT 1u
#define NWB_CSG_INTERVAL_DISPATCH_PUSH_RECEIVER_COUNT 2u
#define NWB_CSG_INTERVAL_DISPATCH_PUSH_LAYER_COUNT 3u
#define NWB_CSG_INTERVAL_DISPATCH_PUSH_WORK_OFFSET_X 0u
#define NWB_CSG_INTERVAL_DISPATCH_PUSH_WORK_OFFSET_Y 1u
#define NWB_CSG_INTERVAL_DISPATCH_PUSH_WORK_EXTENT_X 2u
#define NWB_CSG_INTERVAL_DISPATCH_PUSH_WORK_EXTENT_Y 3u
#define NWB_CSG_INTERVAL_DISPATCH_PUSH_CONSTANT_BYTE_SIZE 32u


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


#endif

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

