// limztudio@gmail.com
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////



#ifndef NWB_GRAPHICS_MESH_MESHLET_CONSTANTS_H
#define NWB_GRAPHICS_MESH_MESHLET_CONSTANTS_H


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


#ifndef NWB_MESH_SHADER_GROUP_SIZE_X
#define NWB_MESH_SHADER_GROUP_SIZE_X 128
#endif

#undef NWB_MESH_SHADER_MAX_VERTICES
#define NWB_MESH_SHADER_MAX_VERTICES 96
#undef NWB_MESH_SHADER_MAX_TRIANGLES
#define NWB_MESH_SHADER_MAX_TRIANGLES 126

#undef NWB_MESHLET_BOUNDS_STRIDE
#define NWB_MESHLET_BOUNDS_STRIDE 24u
#undef NWB_MESHLET_BOUNDS_SPHERE_BYTE_OFFSET
#define NWB_MESHLET_BOUNDS_SPHERE_BYTE_OFFSET 0u
#undef NWB_MESHLET_BOUNDS_CONE_BYTE_OFFSET
#define NWB_MESHLET_BOUNDS_CONE_BYTE_OFFSET 16u
#undef NWB_MESHLET_BOUNDS_PADDING_BYTE_OFFSET
#define NWB_MESHLET_BOUNDS_PADDING_BYTE_OFFSET 20u
#undef NWB_MESHLET_CONE_FLAG_ENABLED
#define NWB_MESHLET_CONE_FLAG_ENABLED 1u
#undef NWB_MESHLET_COUNT_MASK
#define NWB_MESHLET_COUNT_MASK 0xffu
#undef NWB_MESHLET_PRIMITIVE_COUNT_SHIFT
#define NWB_MESHLET_PRIMITIVE_COUNT_SHIFT 8u
#undef NWB_MESHLET_POSITION_COUNT_SHIFT
#define NWB_MESHLET_POSITION_COUNT_SHIFT 16u
#undef NWB_MESHLET_ATTRIBUTE_COUNT_SHIFT
#define NWB_MESHLET_ATTRIBUTE_COUNT_SHIFT 24u
#undef NWB_MESHLET_CONE_AXIS_X_SHIFT
#define NWB_MESHLET_CONE_AXIS_X_SHIFT 0u
#undef NWB_MESHLET_CONE_AXIS_Y_SHIFT
#define NWB_MESHLET_CONE_AXIS_Y_SHIFT 8u
#undef NWB_MESHLET_CONE_CUTOFF_SHIFT
#define NWB_MESHLET_CONE_CUTOFF_SHIFT 16u
#undef NWB_MESHLET_CONE_FLAG_SHIFT
#define NWB_MESHLET_CONE_FLAG_SHIFT 24u
#undef NWB_MESH_MISSING_STREAM_INDEX
#define NWB_MESH_MISSING_STREAM_INDEX 0xffffffffu
#undef NWB_MESHLET_PACKED_BYTE_BITS
#define NWB_MESHLET_PACKED_BYTE_BITS 8u
#undef NWB_MESHLET_PACKED_BYTE_MASK
#define NWB_MESHLET_PACKED_BYTE_MASK 0xffu
#undef NWB_MESHLET_PACKED_WORD_BYTE_MASK
#define NWB_MESHLET_PACKED_WORD_BYTE_MASK 0x3u
#undef NWB_MESHLET_PACKED_HALFWORD_BITS
#define NWB_MESHLET_PACKED_HALFWORD_BITS 16u
#undef NWB_MESHLET_PACKED_HALFWORD_MASK
#define NWB_MESHLET_PACKED_HALFWORD_MASK 0xffffu
#undef NWB_MESHLET_TRIANGLE_INDEX_COUNT
#define NWB_MESHLET_TRIANGLE_INDEX_COUNT 3u
#undef NWB_MESHLET_CONE_AXIS_FALLBACK
#define NWB_MESHLET_CONE_AXIS_FALLBACK 0x8080u
#undef NWB_MESHLET_CONE_AXIS_LENGTH_EPSILON
#define NWB_MESHLET_CONE_AXIS_LENGTH_EPSILON 0.000001
#undef NWB_MESHLET_CONE_AXIS_LENGTH_SQUARED_EPSILON
#define NWB_MESHLET_CONE_AXIS_LENGTH_SQUARED_EPSILON 0.00000001
#undef NWB_MESHLET_REF_WIDTH_U8
#define NWB_MESHLET_REF_WIDTH_U8 0u
#undef NWB_MESHLET_REF_WIDTH_U16
#define NWB_MESHLET_REF_WIDTH_U16 1u
#undef NWB_MESHLET_REF_WIDTH_U32
#define NWB_MESHLET_REF_WIDTH_U32 2u
#undef NWB_MESHLET_REF_ENCODING_WIDTH_MASK
#define NWB_MESHLET_REF_ENCODING_WIDTH_MASK 0x3u
#undef NWB_MESHLET_REF_ENCODING_POSITION_SHIFT
#define NWB_MESHLET_REF_ENCODING_POSITION_SHIFT 0u
#undef NWB_MESHLET_REF_ENCODING_SKIN_SHIFT
#define NWB_MESHLET_REF_ENCODING_SKIN_SHIFT 2u
#undef NWB_MESHLET_REF_ENCODING_NORMAL_SHIFT
#define NWB_MESHLET_REF_ENCODING_NORMAL_SHIFT 4u
#undef NWB_MESHLET_REF_ENCODING_TANGENT_SHIFT
#define NWB_MESHLET_REF_ENCODING_TANGENT_SHIFT 6u
#undef NWB_MESHLET_REF_ENCODING_UV0_SHIFT
#define NWB_MESHLET_REF_ENCODING_UV0_SHIFT 8u
#undef NWB_MESHLET_REF_ENCODING_COLOR_SHIFT
#define NWB_MESHLET_REF_ENCODING_COLOR_SHIFT 10u


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


#endif
#undef NWB_GRAPHICS_MESH_MESHLET_CONSTANTS_H

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

