// limztudio@gmail.com
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


#ifndef NWB_GRAPHICS_MESH_RUNTIME_CONSTANTS_H
#define NWB_GRAPHICS_MESH_RUNTIME_CONSTANTS_H


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


#define NWB_MESH_DISPATCH_FLAG_SCISSOR_CULL (1u << 0u)
#define NWB_MESH_DISPATCH_FLAG_MESHLET_FRUSTUM_CULL (1u << 1u)
#define NWB_MESH_DISPATCH_FLAG_MESHLET_CONE_CULL (1u << 2u)
#define NWB_MESH_DISPATCH_FLAG_CSG_MESHLET_FULLY_REMOVED_CULL (1u << 3u)

// dispatch.w packs flags (low 16) and the shading-model id (high 16).
#define NWB_MESH_DISPATCH_FLAG_MASK 0x0000FFFFu
#define NWB_MESH_DISPATCH_SHADING_MODEL_SHIFT 16u
#define NWB_MESH_DISPATCH_SHADING_MODEL_MASK 0x0000FFFFu

#define NWB_MESH_RASTER_FLAG_CSG_UNAFFECTED (1u << 0u)

#define NWB_MESH_PUSH_DISPATCH_MESHLET_COUNT 0u
#define NWB_MESH_PUSH_DISPATCH_INSTANCE_INDEX 1u
#define NWB_MESH_PUSH_DISPATCH_MATERIAL_CONSTANT_BYTE_OFFSET 2u
#define NWB_MESH_PUSH_DISPATCH_FLAGS 3u
// Frame heap slots share one push-constant lane across both stages.
#define NWB_MESH_PUSH_FRAME_HEAP_SLOT_WORD_OFFSET 12u
#define NWB_MESH_FRAME_HEAP_SLOT_INSTANCE 0u
#define NWB_MESH_FRAME_HEAP_SLOT_MATERIAL_TYPED 1u
#define NWB_MESH_FRAME_HEAP_SLOT_VIEW 2u
// Compute emulation selects its vertex buffer here; raster draws leave it zero.
#define NWB_MESH_FRAME_HEAP_SLOT_GENERATED_VERTEX 3u
#define NWB_MESH_FRAME_HEAP_SLOT_COUNT 4u
#define NWB_MESH_PUSH_CONSTANT_BYTE_SIZE 64u

#define NWB_MESH_VIEW_FRUSTUM_PLANE_COUNT 6
#define NWB_MESH_VIEW_BASE_FLOAT_COUNT 36u
#define NWB_MESH_VIEW_FRUSTUM_PLANE_FLOAT_COUNT 4u
#define NWB_MESH_VIEW_FLOAT_COUNT (NWB_MESH_VIEW_BASE_FLOAT_COUNT + NWB_MESH_VIEW_FRUSTUM_PLANE_COUNT * NWB_MESH_VIEW_FRUSTUM_PLANE_FLOAT_COUNT)

#define NWB_MESH_INSTANCE_ROTATION_FLOAT_OFFSET 0u
#define NWB_MESH_INSTANCE_TRANSLATION_FLOAT_OFFSET 4u
#define NWB_MESH_INSTANCE_MATERIAL_MUTABLE_BYTE_OFFSET_FLOAT_OFFSET 7u
#define NWB_MESH_INSTANCE_SCALE_FLOAT_OFFSET 8u
// Geometry lives in the global heap; instance records carry per-stream slots.
#define NWB_MESH_INSTANCE_GEOMETRY_SLOT_FLOAT_OFFSET 12u
#define NWB_MESH_INSTANCE_GEOMETRY_SLOT_COUNT 12u
// Binding 6 is the CSG context selector.
#define NWB_MESH_INSTANCE_CSG_CONTEXT_HEAP_SLOT 6u
#define NWB_MESH_INSTANCE_FLOAT_COUNT (NWB_MESH_INSTANCE_GEOMETRY_SLOT_FLOAT_OFFSET + NWB_MESH_INSTANCE_GEOMETRY_SLOT_COUNT)

#define NWB_MESH_RASTER_COLOR_LOCATION 0
#define NWB_MESH_RASTER_NORMAL_LOCATION 1
#define NWB_MESH_RASTER_TANGENT_LOCATION 2
#define NWB_MESH_RASTER_UV0_LOCATION 3
#define NWB_MESH_RASTER_WORLD_POSITION_LOCATION 4

#define NWB_MESH_GBUFFER_BASE_COLOR_LOCATION 0
#define NWB_MESH_GBUFFER_NORMAL_LOCATION 1
#define NWB_MESH_GBUFFER_WORLD_POSITION_LOCATION 2
#define NWB_MESH_GBUFFER_SPECULAR_ROUGHNESS_LOCATION 3
#define NWB_MESH_GBUFFER_TARGET_COUNT 4

#define NWB_MESH_EMULATION_VERTEX_BUFFER_INDEX 0
#define NWB_MESH_EMULATION_VERTEX_ATTRIBUTE_COUNT 6
// Byte offsets live here because the f32/f16 buffer is a shared CPU/GPU ABI.
#define NWB_MESH_EMULATION_VERTEX_BYTE_SIZE 64u
#define NWB_MESH_EMULATION_VERTEX_POSITION_LOCATION 0
#define NWB_MESH_EMULATION_VERTEX_NORMAL_LOCATION 1
#define NWB_MESH_EMULATION_VERTEX_TANGENT_LOCATION 2
#define NWB_MESH_EMULATION_VERTEX_UV0_LOCATION 3
#define NWB_MESH_EMULATION_VERTEX_COLOR_LOCATION 4
#define NWB_MESH_EMULATION_VERTEX_WORLD_POSITION_LOCATION 5
#define NWB_MESH_EMULATION_VERTEX_POSITION_BYTE_OFFSET 0u
#define NWB_MESH_EMULATION_VERTEX_NORMAL_BYTE_OFFSET 16u
#define NWB_MESH_EMULATION_VERTEX_TANGENT_BYTE_OFFSET 24u
#define NWB_MESH_EMULATION_VERTEX_UV0_BYTE_OFFSET 32u
#define NWB_MESH_EMULATION_VERTEX_COLOR_BYTE_OFFSET 40u
#define NWB_MESH_EMULATION_VERTEX_WORLD_POSITION_BYTE_OFFSET 48u


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


#endif


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

