// limztudio@gmail.com
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////



#ifndef NWB_GRAPHICS_MESH_RUNTIME_CONSTANTS_H
#define NWB_GRAPHICS_MESH_RUNTIME_CONSTANTS_H


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


#undef NWB_MESH_DISPATCH_FLAG_SCISSOR_CULL
#define NWB_MESH_DISPATCH_FLAG_SCISSOR_CULL (1u << 0u)
#undef NWB_MESH_DISPATCH_FLAG_MESHLET_FRUSTUM_CULL
#define NWB_MESH_DISPATCH_FLAG_MESHLET_FRUSTUM_CULL (1u << 1u)
#undef NWB_MESH_DISPATCH_FLAG_MESHLET_CONE_CULL
#define NWB_MESH_DISPATCH_FLAG_MESHLET_CONE_CULL (1u << 2u)
#undef NWB_MESH_DISPATCH_FLAG_CSG_MESHLET_FULLY_REMOVED_CULL
#define NWB_MESH_DISPATCH_FLAG_CSG_MESHLET_FULLY_REMOVED_CULL (1u << 3u)

#undef NWB_MESH_RASTER_FLAG_CSG_UNAFFECTED
#define NWB_MESH_RASTER_FLAG_CSG_UNAFFECTED (1u << 0u)

#undef NWB_MESH_PUSH_DISPATCH_MESHLET_COUNT
#define NWB_MESH_PUSH_DISPATCH_MESHLET_COUNT 0u
#undef NWB_MESH_PUSH_DISPATCH_INSTANCE_INDEX
#define NWB_MESH_PUSH_DISPATCH_INSTANCE_INDEX 1u
#undef NWB_MESH_PUSH_DISPATCH_MATERIAL_CONSTANT_BYTE_OFFSET
#define NWB_MESH_PUSH_DISPATCH_MATERIAL_CONSTANT_BYTE_OFFSET 2u
#undef NWB_MESH_PUSH_DISPATCH_FLAGS
#define NWB_MESH_PUSH_DISPATCH_FLAGS 3u
#undef NWB_MESH_PUSH_CONSTANT_BYTE_SIZE
#define NWB_MESH_PUSH_CONSTANT_BYTE_SIZE 48u

#undef NWB_MESH_VIEW_FRUSTUM_PLANE_COUNT
#define NWB_MESH_VIEW_FRUSTUM_PLANE_COUNT 6
#undef NWB_MESH_VIEW_BASE_FLOAT_COUNT
#define NWB_MESH_VIEW_BASE_FLOAT_COUNT 36u
#undef NWB_MESH_VIEW_FRUSTUM_PLANE_FLOAT_COUNT
#define NWB_MESH_VIEW_FRUSTUM_PLANE_FLOAT_COUNT 4u
#undef NWB_MESH_VIEW_FLOAT_COUNT
#define NWB_MESH_VIEW_FLOAT_COUNT (NWB_MESH_VIEW_BASE_FLOAT_COUNT + NWB_MESH_VIEW_FRUSTUM_PLANE_COUNT * NWB_MESH_VIEW_FRUSTUM_PLANE_FLOAT_COUNT)

#undef NWB_MESH_INSTANCE_ROTATION_FLOAT_OFFSET
#define NWB_MESH_INSTANCE_ROTATION_FLOAT_OFFSET 0u
#undef NWB_MESH_INSTANCE_TRANSLATION_FLOAT_OFFSET
#define NWB_MESH_INSTANCE_TRANSLATION_FLOAT_OFFSET 4u
#undef NWB_MESH_INSTANCE_MATERIAL_MUTABLE_BYTE_OFFSET_FLOAT_OFFSET
#define NWB_MESH_INSTANCE_MATERIAL_MUTABLE_BYTE_OFFSET_FLOAT_OFFSET 7u
#undef NWB_MESH_INSTANCE_SCALE_FLOAT_OFFSET
#define NWB_MESH_INSTANCE_SCALE_FLOAT_OFFSET 8u
#undef NWB_MESH_INSTANCE_FLOAT_COUNT
#define NWB_MESH_INSTANCE_FLOAT_COUNT 12u

#undef NWB_MESH_RASTER_COLOR_LOCATION
#define NWB_MESH_RASTER_COLOR_LOCATION 0
#undef NWB_MESH_RASTER_NORMAL_LOCATION
#define NWB_MESH_RASTER_NORMAL_LOCATION 1
#undef NWB_MESH_RASTER_TANGENT_LOCATION
#define NWB_MESH_RASTER_TANGENT_LOCATION 2
#undef NWB_MESH_RASTER_UV0_LOCATION
#define NWB_MESH_RASTER_UV0_LOCATION 3
#undef NWB_MESH_RASTER_WORLD_POSITION_LOCATION
#define NWB_MESH_RASTER_WORLD_POSITION_LOCATION 4

#undef NWB_MESH_COLOR_TARGET_LOCATION
#define NWB_MESH_COLOR_TARGET_LOCATION 0

#undef NWB_MESH_GBUFFER_BASE_COLOR_LOCATION
#define NWB_MESH_GBUFFER_BASE_COLOR_LOCATION 0
#undef NWB_MESH_GBUFFER_NORMAL_LOCATION
#define NWB_MESH_GBUFFER_NORMAL_LOCATION 1
#undef NWB_MESH_GBUFFER_WORLD_POSITION_LOCATION
#define NWB_MESH_GBUFFER_WORLD_POSITION_LOCATION 2
#undef NWB_MESH_GBUFFER_TARGET_COUNT
#define NWB_MESH_GBUFFER_TARGET_COUNT 3

#undef NWB_MESH_EMULATION_VERTEX_BUFFER_INDEX
#define NWB_MESH_EMULATION_VERTEX_BUFFER_INDEX 0
#undef NWB_MESH_EMULATION_VERTEX_ATTRIBUTE_COUNT
#define NWB_MESH_EMULATION_VERTEX_ATTRIBUTE_COUNT 6
#undef NWB_MESH_EMULATION_VERTEX_FLOAT_COUNT
#define NWB_MESH_EMULATION_VERTEX_FLOAT_COUNT 24u
#undef NWB_MESH_EMULATION_VERTEX_POSITION_LOCATION
#define NWB_MESH_EMULATION_VERTEX_POSITION_LOCATION 0
#undef NWB_MESH_EMULATION_VERTEX_NORMAL_LOCATION
#define NWB_MESH_EMULATION_VERTEX_NORMAL_LOCATION 1
#undef NWB_MESH_EMULATION_VERTEX_TANGENT_LOCATION
#define NWB_MESH_EMULATION_VERTEX_TANGENT_LOCATION 2
#undef NWB_MESH_EMULATION_VERTEX_UV0_LOCATION
#define NWB_MESH_EMULATION_VERTEX_UV0_LOCATION 3
#undef NWB_MESH_EMULATION_VERTEX_COLOR_LOCATION
#define NWB_MESH_EMULATION_VERTEX_COLOR_LOCATION 4
#undef NWB_MESH_EMULATION_VERTEX_WORLD_POSITION_LOCATION
#define NWB_MESH_EMULATION_VERTEX_WORLD_POSITION_LOCATION 5
#undef NWB_MESH_EMULATION_VERTEX_POSITION_FLOAT_OFFSET
#define NWB_MESH_EMULATION_VERTEX_POSITION_FLOAT_OFFSET 0u
#undef NWB_MESH_EMULATION_VERTEX_NORMAL_FLOAT_OFFSET
#define NWB_MESH_EMULATION_VERTEX_NORMAL_FLOAT_OFFSET 4u
#undef NWB_MESH_EMULATION_VERTEX_TANGENT_FLOAT_OFFSET
#define NWB_MESH_EMULATION_VERTEX_TANGENT_FLOAT_OFFSET 8u
#undef NWB_MESH_EMULATION_VERTEX_UV0_FLOAT_OFFSET
#define NWB_MESH_EMULATION_VERTEX_UV0_FLOAT_OFFSET 12u
#undef NWB_MESH_EMULATION_VERTEX_COLOR_FLOAT_OFFSET
#define NWB_MESH_EMULATION_VERTEX_COLOR_FLOAT_OFFSET 16u
#undef NWB_MESH_EMULATION_VERTEX_WORLD_POSITION_FLOAT_OFFSET
#define NWB_MESH_EMULATION_VERTEX_WORLD_POSITION_FLOAT_OFFSET 20u


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


#endif
#undef NWB_GRAPHICS_MESH_RUNTIME_CONSTANTS_H

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

