// limztudio@gmail.com
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////



#ifndef NWB_AVBOIT_BINDING_SLOTS_H
#define NWB_AVBOIT_BINDING_SLOTS_H


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


#undef NWB_AVBOIT_TRANSPARENT_SET
#define NWB_AVBOIT_TRANSPARENT_SET 1
#undef NWB_AVBOIT_COMPUTE_SET
#define NWB_AVBOIT_COMPUTE_SET 0

#undef NWB_AVBOIT_BINDING_OPAQUE_DEPTH
#define NWB_AVBOIT_BINDING_OPAQUE_DEPTH 0
#undef NWB_AVBOIT_BINDING_POINT_SAMPLER
#define NWB_AVBOIT_BINDING_POINT_SAMPLER 1

#undef NWB_AVBOIT_OCCUPANCY_BINDING_COVERAGE_WORDS
#define NWB_AVBOIT_OCCUPANCY_BINDING_COVERAGE_WORDS 2

#undef NWB_AVBOIT_DEPTH_WARP_BINDING_COVERAGE_WORDS
#define NWB_AVBOIT_DEPTH_WARP_BINDING_COVERAGE_WORDS 0
#undef NWB_AVBOIT_DEPTH_WARP_BINDING_DEPTH_WARP
#define NWB_AVBOIT_DEPTH_WARP_BINDING_DEPTH_WARP 1
#undef NWB_AVBOIT_DEPTH_WARP_BINDING_CONTROL
#define NWB_AVBOIT_DEPTH_WARP_BINDING_CONTROL 2

#undef NWB_AVBOIT_EXTINCTION_BINDING_DEPTH_WARP
#define NWB_AVBOIT_EXTINCTION_BINDING_DEPTH_WARP 2
#undef NWB_AVBOIT_EXTINCTION_BINDING_CONTROL
#define NWB_AVBOIT_EXTINCTION_BINDING_CONTROL 3
#undef NWB_AVBOIT_EXTINCTION_BINDING_EXTINCTION
#define NWB_AVBOIT_EXTINCTION_BINDING_EXTINCTION 4
#undef NWB_AVBOIT_EXTINCTION_BINDING_OVERFLOW_DEPTH
#define NWB_AVBOIT_EXTINCTION_BINDING_OVERFLOW_DEPTH 5

#undef NWB_AVBOIT_INTEGRATE_BINDING_EXTINCTION
#define NWB_AVBOIT_INTEGRATE_BINDING_EXTINCTION 0
#undef NWB_AVBOIT_INTEGRATE_BINDING_TRANSMITTANCE
#define NWB_AVBOIT_INTEGRATE_BINDING_TRANSMITTANCE 1
#undef NWB_AVBOIT_INTEGRATE_BINDING_CONTROL
#define NWB_AVBOIT_INTEGRATE_BINDING_CONTROL 2
#undef NWB_AVBOIT_INTEGRATE_BINDING_OVERFLOW_DEPTH
#define NWB_AVBOIT_INTEGRATE_BINDING_OVERFLOW_DEPTH 3

#undef NWB_AVBOIT_ACCUMULATE_BINDING_DEPTH_WARP
#define NWB_AVBOIT_ACCUMULATE_BINDING_DEPTH_WARP 0
#undef NWB_AVBOIT_ACCUMULATE_BINDING_TRANSMITTANCE
#define NWB_AVBOIT_ACCUMULATE_BINDING_TRANSMITTANCE 1
#undef NWB_AVBOIT_ACCUMULATE_BINDING_CONTROL
#define NWB_AVBOIT_ACCUMULATE_BINDING_CONTROL 2
#undef NWB_AVBOIT_ACCUMULATE_BINDING_LINEAR_SAMPLER
#define NWB_AVBOIT_ACCUMULATE_BINDING_LINEAR_SAMPLER 3

#undef NWB_AVBOIT_ACCUM_COLOR_LOCATION
#define NWB_AVBOIT_ACCUM_COLOR_LOCATION 0
#undef NWB_AVBOIT_ACCUM_EXTINCTION_LOCATION
#define NWB_AVBOIT_ACCUM_EXTINCTION_LOCATION 1
#undef NWB_AVBOIT_ACCUM_TARGET_COUNT
#define NWB_AVBOIT_ACCUM_TARGET_COUNT 2


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


#endif
#undef NWB_AVBOIT_BINDING_SLOTS_H

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

