
#ifndef NWB_AVBOIT_CONSTANTS_H
#define NWB_AVBOIT_CONSTANTS_H


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


#define NWB_AVBOIT_WARP_INVALID 0xffffffffu
#define NWB_AVBOIT_OVERFLOW_INVALID 0xffffffffu
#define NWB_AVBOIT_EXTINCTION_SLICES_PER_WORD 4u
#define NWB_AVBOIT_EXTINCTION_BYTE_MASK 0xffu
#define NWB_AVBOIT_EXTINCTION_BYTE_BITS 8u
#define NWB_AVBOIT_EXTINCTION_SATURATION 16.0
#define NWB_AVBOIT_COVERAGE_SLICES_PER_WORD 32u
#define NWB_AVBOIT_COVERAGE_WORD_SHIFT 5u
#define NWB_AVBOIT_COVERAGE_BIT_MASK 31u
#define NWB_AVBOIT_TRANSMITTANCE_IMAGE_FORMAT "r16f"
#if defined(__cplusplus)
#define NWB_AVBOIT_TRANSMITTANCE_CORE_FORMAT NWB::Core::Format::R16_FLOAT
#endif
#define NWB_AVBOIT_DEPTH_WARP_GROUP_SIZE_X 1
#define NWB_AVBOIT_DEPTH_WARP_DISPATCH_GROUP_COUNT_X 1u
#define NWB_AVBOIT_INTEGRATE_GROUP_SIZE_X 64

#define NWB_AVBOIT_CONTROL_ACTIVE_PHYSICAL_SLICES 0
#define NWB_AVBOIT_CONTROL_COMPRESSION_SHIFT 1
#define NWB_AVBOIT_CONTROL_VIRTUAL_SLICE_COUNT 2
#define NWB_AVBOIT_CONTROL_PHYSICAL_SLICE_COUNT 3
#define NWB_AVBOIT_CONTROL_LOW_WIDTH 4
#define NWB_AVBOIT_CONTROL_LOW_HEIGHT 5
#define NWB_AVBOIT_CONTROL_FULL_WIDTH 6
#define NWB_AVBOIT_CONTROL_FULL_HEIGHT 7
#define NWB_AVBOIT_CONTROL_WORD_COUNT 8u

#define NWB_AVBOIT_PUSH_FRAME_WORD_OFFSET 0u
#define NWB_AVBOIT_PUSH_VOLUME_WORD_OFFSET 4u
#define NWB_AVBOIT_PUSH_PARAMS_WORD_OFFSET 8u
#define NWB_AVBOIT_PUSH_FRAME_FULL_WIDTH 0u
#define NWB_AVBOIT_PUSH_FRAME_FULL_HEIGHT 1u
#define NWB_AVBOIT_PUSH_FRAME_LOW_WIDTH 2u
#define NWB_AVBOIT_PUSH_FRAME_LOW_HEIGHT 3u
#define NWB_AVBOIT_PUSH_VOLUME_VIRTUAL_SLICE_COUNT 0u
#define NWB_AVBOIT_PUSH_VOLUME_PHYSICAL_SLICE_COUNT 1u
#define NWB_AVBOIT_PUSH_VOLUME_EXTINCTION_WORD_COUNT 2u
#define NWB_AVBOIT_PUSH_VOLUME_COVERAGE_WORD_COUNT 3u
#define NWB_AVBOIT_PUSH_PARAMS_EXTINCTION_FIXED_SCALE 1u
#define NWB_AVBOIT_PUSH_PARAMS_SELF_OCCLUSION_SLICE_BIAS 2u
#define NWB_AVBOIT_PUSH_CONSTANT_BYTE_SIZE 48u
#define NWB_AVBOIT_DRAW_PUSH_CONSTANT_BYTE_SIZE 96u


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


#endif


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

