// limztudio@gmail.com
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////



#ifndef NWB_AVBOIT_CONSTANTS_H
#define NWB_AVBOIT_CONSTANTS_H


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


#undef NWB_AVBOIT_WARP_INVALID
#define NWB_AVBOIT_WARP_INVALID 0xffffffffu
#undef NWB_AVBOIT_OVERFLOW_INVALID
#define NWB_AVBOIT_OVERFLOW_INVALID 0xffffffffu
#undef NWB_AVBOIT_EXTINCTION_SLICES_PER_WORD
#define NWB_AVBOIT_EXTINCTION_SLICES_PER_WORD 4u
#undef NWB_AVBOIT_EXTINCTION_BYTE_MASK
#define NWB_AVBOIT_EXTINCTION_BYTE_MASK 0xffu
#undef NWB_AVBOIT_EXTINCTION_BYTE_BITS
#define NWB_AVBOIT_EXTINCTION_BYTE_BITS 8u
#undef NWB_AVBOIT_EXTINCTION_SATURATION
#define NWB_AVBOIT_EXTINCTION_SATURATION 16.0
#undef NWB_AVBOIT_COVERAGE_SLICES_PER_WORD
#define NWB_AVBOIT_COVERAGE_SLICES_PER_WORD 32u
#undef NWB_AVBOIT_COVERAGE_WORD_SHIFT
#define NWB_AVBOIT_COVERAGE_WORD_SHIFT 5u
#undef NWB_AVBOIT_COVERAGE_BIT_MASK
#define NWB_AVBOIT_COVERAGE_BIT_MASK 31u
#undef NWB_AVBOIT_TRANSMITTANCE_IMAGE_FORMAT
#define NWB_AVBOIT_TRANSMITTANCE_IMAGE_FORMAT "r16f"
#if defined(__cplusplus)
#undef NWB_AVBOIT_TRANSMITTANCE_CORE_FORMAT
#define NWB_AVBOIT_TRANSMITTANCE_CORE_FORMAT NWB::Core::Format::R16_FLOAT
#endif
#undef NWB_AVBOIT_DEPTH_WARP_GROUP_SIZE_X
#define NWB_AVBOIT_DEPTH_WARP_GROUP_SIZE_X 1
#undef NWB_AVBOIT_DEPTH_WARP_DISPATCH_GROUP_COUNT_X
#define NWB_AVBOIT_DEPTH_WARP_DISPATCH_GROUP_COUNT_X 1u
#undef NWB_AVBOIT_INTEGRATE_GROUP_SIZE_X
#define NWB_AVBOIT_INTEGRATE_GROUP_SIZE_X 64

#undef NWB_AVBOIT_CONTROL_ACTIVE_PHYSICAL_SLICES
#define NWB_AVBOIT_CONTROL_ACTIVE_PHYSICAL_SLICES 0
#undef NWB_AVBOIT_CONTROL_COMPRESSION_SHIFT
#define NWB_AVBOIT_CONTROL_COMPRESSION_SHIFT 1
#undef NWB_AVBOIT_CONTROL_VIRTUAL_SLICE_COUNT
#define NWB_AVBOIT_CONTROL_VIRTUAL_SLICE_COUNT 2
#undef NWB_AVBOIT_CONTROL_PHYSICAL_SLICE_COUNT
#define NWB_AVBOIT_CONTROL_PHYSICAL_SLICE_COUNT 3
#undef NWB_AVBOIT_CONTROL_LOW_WIDTH
#define NWB_AVBOIT_CONTROL_LOW_WIDTH 4
#undef NWB_AVBOIT_CONTROL_LOW_HEIGHT
#define NWB_AVBOIT_CONTROL_LOW_HEIGHT 5
#undef NWB_AVBOIT_CONTROL_FULL_WIDTH
#define NWB_AVBOIT_CONTROL_FULL_WIDTH 6
#undef NWB_AVBOIT_CONTROL_FULL_HEIGHT
#define NWB_AVBOIT_CONTROL_FULL_HEIGHT 7
#undef NWB_AVBOIT_CONTROL_WORD_COUNT
#define NWB_AVBOIT_CONTROL_WORD_COUNT 8u

#undef NWB_AVBOIT_PUSH_FRAME_WORD_OFFSET
#define NWB_AVBOIT_PUSH_FRAME_WORD_OFFSET 0u
#undef NWB_AVBOIT_PUSH_VOLUME_WORD_OFFSET
#define NWB_AVBOIT_PUSH_VOLUME_WORD_OFFSET 4u
#undef NWB_AVBOIT_PUSH_PARAMS_WORD_OFFSET
#define NWB_AVBOIT_PUSH_PARAMS_WORD_OFFSET 8u
#undef NWB_AVBOIT_PUSH_FRAME_FULL_WIDTH
#define NWB_AVBOIT_PUSH_FRAME_FULL_WIDTH 0u
#undef NWB_AVBOIT_PUSH_FRAME_FULL_HEIGHT
#define NWB_AVBOIT_PUSH_FRAME_FULL_HEIGHT 1u
#undef NWB_AVBOIT_PUSH_FRAME_LOW_WIDTH
#define NWB_AVBOIT_PUSH_FRAME_LOW_WIDTH 2u
#undef NWB_AVBOIT_PUSH_FRAME_LOW_HEIGHT
#define NWB_AVBOIT_PUSH_FRAME_LOW_HEIGHT 3u
#undef NWB_AVBOIT_PUSH_VOLUME_VIRTUAL_SLICE_COUNT
#define NWB_AVBOIT_PUSH_VOLUME_VIRTUAL_SLICE_COUNT 0u
#undef NWB_AVBOIT_PUSH_VOLUME_PHYSICAL_SLICE_COUNT
#define NWB_AVBOIT_PUSH_VOLUME_PHYSICAL_SLICE_COUNT 1u
#undef NWB_AVBOIT_PUSH_VOLUME_EXTINCTION_WORD_COUNT
#define NWB_AVBOIT_PUSH_VOLUME_EXTINCTION_WORD_COUNT 2u
#undef NWB_AVBOIT_PUSH_VOLUME_COVERAGE_WORD_COUNT
#define NWB_AVBOIT_PUSH_VOLUME_COVERAGE_WORD_COUNT 3u
#undef NWB_AVBOIT_PUSH_PARAMS_EXTINCTION_FIXED_SCALE
#define NWB_AVBOIT_PUSH_PARAMS_EXTINCTION_FIXED_SCALE 1u
#undef NWB_AVBOIT_PUSH_PARAMS_SELF_OCCLUSION_SLICE_BIAS
#define NWB_AVBOIT_PUSH_PARAMS_SELF_OCCLUSION_SLICE_BIAS 2u
#undef NWB_AVBOIT_PUSH_CONSTANT_BYTE_SIZE
#define NWB_AVBOIT_PUSH_CONSTANT_BYTE_SIZE 48u
#undef NWB_AVBOIT_DRAW_PUSH_CONSTANT_BYTE_SIZE
#define NWB_AVBOIT_DRAW_PUSH_CONSTANT_BYTE_SIZE 96u


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


#endif
#undef NWB_AVBOIT_CONSTANTS_H

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

