// limztudio@gmail.com
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


#include "shader_cook.h"


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


NWB_CORE_BEGIN


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


#if defined(NWB_COOK)


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


namespace ShaderCook{


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


struct SortedDependencyItem{
    AString canonicalPath;
    Path path;
};


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


template<typename MapT>
static CookVector<Pair<const AString*, const typename MapT::mapped_type*>> SortedDefineEntries(const MapT& map){
    using EntryPtr = Pair<const AString*, const typename MapT::mapped_type*>;
    CookVector<EntryPtr> entries;
    entries.reserve(map.size());
    for(const auto& [name, value] : map)
        entries.push_back({ &name, &value });
    Sort(entries.begin(), entries.end(), [](const EntryPtr& lhs, const EntryPtr& rhs){ return *lhs.first < *rhs.first; });
    return entries;
}


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


void ExpandDefineCombinations(
    const CookMap<AString, CookVector<AString>>& defineValues,
    CookVector<DefineCombo>& outCombinations
){
    outCombinations.clear();
    outCombinations.push_back({});

    for(const auto& [defineName, pValues] : SortedDefineEntries(defineValues)){
        const CookVector<AString>& values = *pValues;
        CookVector<DefineCombo> expanded;
        expanded.reserve(outCombinations.size() * values.size());

        for(const DefineCombo& combo : outCombinations){
            for(const AString& value : values){
                DefineCombo copy = combo;
                copy[*defineName] = value;
                expanded.push_back(Move(copy));
            }
        }

        outCombinations = Move(expanded);
    }
}


AString BuildVariantName(const DefineCombo& combo){
    if(combo.empty())
        return "default";

    AString variantName;
    bool first = true;
    for(const auto& [defineName, pValue] : SortedDefineEntries(combo)){
        if(!first)
            variantName += ';';
        first = false;

        variantName += *defineName;
        variantName += '=';
        variantName += *pValue;
    }

    return variantName;
}


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


static bool ParseDefineValues(const AStringView valueText, CookVector<AString>& outValues){
    outValues.clear();

    usize begin = 0;
    while(begin <= valueText.size()){
        usize commaPos = valueText.find(',', begin);
        if(commaPos == AStringView::npos)
            commaPos = valueText.size();

        const AString value = Trim(valueText.substr(begin, commaPos - begin));
        if(value.empty())
            return false;

        outValues.push_back(value);
        if(commaPos == valueText.size())
            break;

        begin = commaPos + 1;
    }

    return true;
}


static bool ValidateDefaultVariant(const ManifestEntry& entry, AString& outError){
    if(entry.defaultVariant.empty())
        return true;

    if(entry.defaultVariant == "default"){
        if(entry.defineValues.empty())
            return true;

        outError = StringFormat(
            "Manifest parsing failed: entry '{}' default variant '{}' is not generated by entry.define.* values",
            entry.name,
            entry.defaultVariant
        );
        return false;
    }

    if(entry.defineValues.empty()){
        outError = StringFormat(
            "Manifest parsing failed: entry '{}' default variant '{}' is not generated by entry.define.* values",
            entry.name,
            entry.defaultVariant
        );
        return false;
    }

    CookHashSet<AString> seenDefines;
    usize begin = 0;
    while(begin < entry.defaultVariant.size()){
        usize segmentEnd = entry.defaultVariant.find(';', begin);
        if(segmentEnd == AString::npos)
            segmentEnd = entry.defaultVariant.size();

        const AString segment = Trim(AStringView(entry.defaultVariant).substr(begin, segmentEnd - begin));
        if(segment.empty()){
            outError = StringFormat(
                "Manifest parsing failed: entry '{}' default variant '{}' has invalid empty assignment",
                entry.name,
                entry.defaultVariant
            );
            return false;
        }

        const usize equalPos = segment.find('=');
        if(equalPos == AString::npos || equalPos == 0 || equalPos + 1 >= segment.size()){
            outError = StringFormat(
                "Manifest parsing failed: entry '{}' default variant '{}' has invalid assignment '{}'",
                entry.name,
                entry.defaultVariant,
                segment
            );
            return false;
        }

        const AString defineName = Trim(AStringView(segment).substr(0, equalPos));
        const AString defineValue = Trim(AStringView(segment).substr(equalPos + 1));
        if(defineName.empty() || defineValue.empty()){
            outError = StringFormat(
                "Manifest parsing failed: entry '{}' default variant '{}' has invalid assignment '{}'",
                entry.name,
                entry.defaultVariant,
                segment
            );
            return false;
        }
        const auto defineIt = entry.defineValues.find(defineName);
        if(defineIt == entry.defineValues.end()){
            outError = StringFormat(
                "Manifest parsing failed: entry '{}' default variant '{}' references unknown define '{}'",
                entry.name,
                entry.defaultVariant,
                defineName
            );
            return false;
        }

        bool valueFound = false;
        for(const AString& allowedValue : defineIt.value()){
            if(allowedValue == defineValue){
                valueFound = true;
                break;
            }
        }
        if(!valueFound){
            outError = StringFormat(
                "Manifest parsing failed: entry '{}' default variant '{}' has unsupported value '{}' for define '{}'",
                entry.name,
                entry.defaultVariant,
                defineValue,
                defineName
            );
            return false;
        }

        if(!seenDefines.insert(defineName).second){
            outError = StringFormat(
                "Manifest parsing failed: entry '{}' default variant '{}' assigns define '{}' more than once",
                entry.name,
                entry.defaultVariant,
                defineName
            );
            return false;
        }

        begin = segmentEnd + 1;
    }

    if(seenDefines.size() != entry.defineValues.size()){
        outError = StringFormat(
            "Manifest parsing failed: entry '{}' default variant '{}' must assign all defines",
            entry.name,
            entry.defaultVariant
        );
        return false;
    }

    return true;
}


static bool ValidateManifestEntries(const CookVector<ManifestEntry>& entries, AString& outError){
    CookHashSet<Name> uniqueEntryNames;
    for(const ManifestEntry& entry : entries){
        const Name entryName(entry.name.c_str());
        if(!uniqueEntryNames.insert(entryName).second){
            outError = StringFormat(
                "Manifest parsing failed: duplicated entry.name '{}' is not allowed",
                entry.name
            );
            return false;
        }
        if(!ValidateDefaultVariant(entry, outError))
            return false;
    }

    return true;
}


static bool ExtractIncludeName(const AStringView line, AString& outIncludeName){
    outIncludeName.clear();

    usize cursor = 0;
    while(cursor < line.size() && IsAsciiSpace(line[cursor]))
        ++cursor;

    if(cursor >= line.size() || line[cursor] != '#')
        return false;

    ++cursor;
    while(cursor < line.size() && IsAsciiSpace(line[cursor]))
        ++cursor;

    static constexpr AStringView s_IncludeKeyword = "include";
    if(line.substr(cursor, s_IncludeKeyword.size()) != s_IncludeKeyword)
        return false;
    cursor += s_IncludeKeyword.size();

    while(cursor < line.size() && IsAsciiSpace(line[cursor]))
        ++cursor;

    if(cursor >= line.size() || line[cursor] != '"')
        return false;
    ++cursor;

    const usize closingQuote = line.find('"', cursor);
    if(closingQuote == AStringView::npos || closingQuote <= cursor)
        return false;

    outIncludeName = AString(line.substr(cursor, closingQuote - cursor));
    return !outIncludeName.empty();
}


static bool ResolveIncludeFile(const AStringView includeName, const Path& sourceDirectory, const CookVector<Path>& includeDirectories, Path& outPath){
    ErrorCode errorCode;

    const Path localCandidate = (sourceDirectory / Path(includeName)).lexically_normal();
    if(FileExists(localCandidate, errorCode)){
        outPath = localCandidate;
        return true;
    }

    for(const Path& includeDirectory : includeDirectories){
        const Path includeCandidate = (includeDirectory / Path(includeName)).lexically_normal();
        if(FileExists(includeCandidate, errorCode)){
            outPath = includeCandidate;
            return true;
        }
    }

    return false;
}


static bool CollectDependenciesRecursive(const Path& dependencyPath, const CookVector<Path>& includeDirectories, CookHashSet<AString>& inOutVisitedPaths, CookVector<Path>& inOutDependencies, AString& outError){
    ErrorCode errorCode;

    const Path absolutePath = AbsolutePath(dependencyPath, errorCode).lexically_normal();
    if(errorCode){
        outError = StringFormat(
            "Failed to resolve dependency path '{}' : {}",
            PathToString(dependencyPath),
            errorCode.message()
        );
        return false;
    }

    const AString canonicalPathKey = CanonicalizeText(PathToString(absolutePath));
    if(!inOutVisitedPaths.insert(canonicalPathKey).second)
        return true;

    AString sourceText;
    if(!ReadTextFile(absolutePath, sourceText)){
        outError = StringFormat("Failed to read dependency '{}'", PathToString(absolutePath));
        return false;
    }

    inOutDependencies.push_back(absolutePath);

    AStringStream sourceStream(sourceText);
    AString line;
    while(ReadTextLine(sourceStream, line)){
        TrimTrailingCarriageReturn(line);

        AString includeName;
        if(!ExtractIncludeName(line, includeName))
            continue;

        Path includePath;
        if(!ResolveIncludeFile(includeName, absolutePath.parent_path(), includeDirectories, includePath)){
            outError = StringFormat(
                "Unable to resolve include '{}' from '{}'",
                includeName,
                PathToString(absolutePath)
            );
            return false;
        }

        if(!CollectDependenciesRecursive(includePath, includeDirectories, inOutVisitedPaths, inOutDependencies, outError))
            return false;
    }

    return true;
}


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


bool ParseManifestFile(const Path& manifestPath, ManifestData& outManifest, AString& outError){
    outManifest = {};
    outManifest.volumeName = "graphics";
    outManifest.segmentSize = s_DefaultSegmentSize;
    outManifest.metadataSize = s_DefaultMetadataSize;

    AString manifestText;
    if(!ReadTextFile(manifestPath, manifestText)){
        outError = StringFormat("Failed to read manifest '{}'", PathToString(manifestPath));
        return false;
    }
    StripUtf8Bom(manifestText);

    bool parsingEntry = false;
    ManifestEntry currentEntry;

    AStringStream stream(manifestText);
    AString line;
    usize lineNumber = 0;
    while(ReadTextLine(stream, line)){
        ++lineNumber;

        TrimTrailingCarriageReturn(line);

        const AString trimmed = Trim(line);
        if(trimmed.empty())
            continue;
        if(trimmed[0] == '#')
            continue;

        if(trimmed == "entry.begin"){
            if(parsingEntry){
                outError = StringFormat("Manifest line {}: nested entry.begin is not allowed", lineNumber);
                return false;
            }

            parsingEntry = true;
            currentEntry = {};
            currentEntry.compiler = "glslang";
            currentEntry.entryPoint = "main";
            continue;
        }
        if(trimmed == "entry.end"){
            if(!parsingEntry){
                outError = StringFormat("Manifest line {}: entry.end without entry.begin", lineNumber);
                return false;
            }

            if(currentEntry.name.empty() || currentEntry.stage.empty() || currentEntry.source.empty()){
                outError = StringFormat(
                    "Manifest line {}: entry requires name/stage/source (entry.name, entry.stage, entry.source)",
                    lineNumber
                );
                return false;
            }

            currentEntry.name = CanonicalizeText(currentEntry.name);
            currentEntry.compiler = currentEntry.compiler.empty() ? AString("glslang") : CanonicalizeText(currentEntry.compiler);
            currentEntry.stage = CanonicalizeText(currentEntry.stage);
            currentEntry.targetProfile = CanonicalizeText(currentEntry.targetProfile);
            currentEntry.defaultVariant = currentEntry.defaultVariant.empty()
                ? AString()
                : CanonicalizeText(currentEntry.defaultVariant);

            outManifest.entries.push_back(currentEntry);
            parsingEntry = false;
            continue;
        }

        const usize equalPos = trimmed.find('=');
        if(equalPos == AString::npos){
            outError = StringFormat("Manifest line {}: expected key=value", lineNumber);
            return false;
        }

        const AString key = Trim(AStringView(trimmed).substr(0, equalPos));
        const AString value = Trim(AStringView(trimmed).substr(equalPos + 1));
        if(key.empty()){
            outError = StringFormat("Manifest line {}: key is empty", lineNumber);
            return false;
        }

        if(!parsingEntry){
            if(key == "volume.name"){
                outManifest.volumeName = CanonicalizeText(value);
                continue;
            }
            if(key == "volume.segment_size"){
                u64 parsedValue = 0;
                if(!ParseU64(value, parsedValue) || parsedValue == 0){
                    outError = StringFormat("Manifest line {}: invalid volume.segment_size '{}'", lineNumber, value);
                    return false;
                }
                outManifest.segmentSize = parsedValue;
                continue;
            }
            if(key == "volume.metadata_size"){
                u64 parsedValue = 0;
                if(!ParseU64(value, parsedValue)){
                    outError = StringFormat("Manifest line {}: invalid volume.metadata_size '{}'", lineNumber, value);
                    return false;
                }
                outManifest.metadataSize = parsedValue;
                continue;
            }
            if(key == "include_root"){
                if(value.empty()){
                    outError = StringFormat("Manifest line {}: include_root cannot be empty", lineNumber);
                    return false;
                }
                outManifest.includeRoots.push_back(value);
                continue;
            }

            outError = StringFormat("Manifest line {}: unsupported global key '{}'", lineNumber, key);
            return false;
        }

        if(key == "entry.name"){
            currentEntry.name = value;
            continue;
        }
        if(key == "entry.compiler"){
            currentEntry.compiler = value;
            continue;
        }
        if(key == "entry.stage"){
            currentEntry.stage = value;
            continue;
        }
        if(key == "entry.target_profile"){
            currentEntry.targetProfile = value;
            continue;
        }
        if(key == "entry.entry_point"){
            currentEntry.entryPoint = value.empty() ? AString("main") : value;
            continue;
        }
        if(key == "entry.source"){
            currentEntry.source = value;
            continue;
        }
        if(key == "entry.default_variant"){
            currentEntry.defaultVariant = value;
            continue;
        }

        static constexpr AStringView s_EntryDefinePrefix = "entry.define.";
        if(key.starts_with(s_EntryDefinePrefix)){
            const AString defineName = Trim(AStringView(key).substr(s_EntryDefinePrefix.size()));
            if(defineName.empty()){
                outError = StringFormat("Manifest line {}: define key is empty", lineNumber);
                return false;
            }

            CookVector<AString> defineValues;
            if(!ParseDefineValues(value, defineValues)){
                outError = StringFormat("Manifest line {}: define '{}' has invalid values '{}'", lineNumber, defineName, value);
                return false;
            }

            currentEntry.defineValues[defineName] = defineValues;
            continue;
        }

        outError = StringFormat("Manifest line {}: unsupported entry key '{}'", lineNumber, key);
        return false;
    }

    if(parsingEntry){
        outError = "Manifest parsing failed: missing trailing entry.end";
        return false;
    }
    if(outManifest.volumeName.empty()){
        outError = "Manifest parsing failed: volume.name is empty";
        return false;
    }
    if(outManifest.segmentSize == 0){
        outError = "Manifest parsing failed: volume.segment_size is zero";
        return false;
    }
    if(outManifest.entries.empty()){
        outError = "Manifest parsing failed: no entry was defined";
        return false;
    }
    if(!ValidateManifestEntries(outManifest.entries, outError))
        return false;

    return true;
}


bool GatherShaderDependencies(const Path& sourcePath, const CookVector<Path>& includeDirectories, CookVector<Path>& outDependencies, AString& outError){
    outDependencies.clear();

    CookHashSet<AString> visited;
    if(!CollectDependenciesRecursive(sourcePath, includeDirectories, visited, outDependencies, outError))
        return false;

    return true;
}


bool ComputeSourceChecksum(const ManifestEntry& entry, const AStringView variantName, const CookVector<Path>& dependencies, u64& outChecksum, AString& outError){
    ErrorCode errorCode;

    outChecksum = FNV64_OFFSET_BASIS;

    AString header;
    header.reserve(
        entry.name.size()
        + entry.compiler.size()
        + entry.stage.size()
        + entry.targetProfile.size()
        + entry.entryPoint.size()
        + variantName.size()
        + 6
    );
    header += entry.name;
    header += '\n';
    header += entry.compiler;
    header += '\n';
    header += entry.stage;
    header += '\n';
    header += entry.targetProfile;
    header += '\n';
    header += entry.entryPoint;
    header += '\n';
    header += variantName;
    header += '\n';

    outChecksum = UpdateFnv64(outChecksum, reinterpret_cast<const u8*>(header.data()), header.size());

    CookVector<SortedDependencyItem> sortedDependencies;
    sortedDependencies.reserve(dependencies.size());
    for(const Path& dependency : dependencies){
        SortedDependencyItem item;
        item.canonicalPath = CanonicalizeText(PathToString(dependency));
        item.path = dependency;
        sortedDependencies.push_back(Move(item));
    }

    Sort(
        sortedDependencies.begin(),
        sortedDependencies.end(),
        [](const SortedDependencyItem& lhs, const SortedDependencyItem& rhs){
            return lhs.canonicalPath < rhs.canonicalPath;
        }
    );

    for(const SortedDependencyItem& item : sortedDependencies){
        AString dependencyPrefix = item.canonicalPath;
        dependencyPrefix += '\n';
        outChecksum = UpdateFnv64(
            outChecksum,
            reinterpret_cast<const u8*>(dependencyPrefix.data()),
            dependencyPrefix.size()
        );

        CookVector<u8> dependencyBytes;
        if(!ReadBinaryFile(item.path, dependencyBytes, errorCode)){
            outError = StringFormat("Failed to read dependency file '{}'", item.canonicalPath);
            return false;
        }
        if(!dependencyBytes.empty()){
            outChecksum = UpdateFnv64(
                outChecksum,
                dependencyBytes.data(),
                dependencyBytes.size()
            );
        }

        const u8 zeroByte = 0;
        outChecksum = UpdateFnv64(outChecksum, &zeroByte, 1);
    }

    return true;
}


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


};


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


#endif


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


NWB_CORE_END


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

