// limztudio@gmail.com
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////



#ifndef NWB_SKINNED_MESH_BINDING_SLOTS_H
#define NWB_SKINNED_MESH_BINDING_SLOTS_H


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


#undef NWB_SKINNED_MESH_SET
#define NWB_SKINNED_MESH_SET 0
#undef NWB_SKINNED_MESH_BOUNDS_SET
#define NWB_SKINNED_MESH_BOUNDS_SET 0

#undef NWB_SKINNED_MESH_BINDING_REST_POSITION
#define NWB_SKINNED_MESH_BINDING_REST_POSITION 0
#undef NWB_SKINNED_MESH_BINDING_SKINNED_POSITION
#define NWB_SKINNED_MESH_BINDING_SKINNED_POSITION 1
#undef NWB_SKINNED_MESH_BINDING_REST_NORMAL
#define NWB_SKINNED_MESH_BINDING_REST_NORMAL 2
#undef NWB_SKINNED_MESH_BINDING_SKINNED_NORMAL
#define NWB_SKINNED_MESH_BINDING_SKINNED_NORMAL 3
#undef NWB_SKINNED_MESH_BINDING_REST_TANGENT
#define NWB_SKINNED_MESH_BINDING_REST_TANGENT 4
#undef NWB_SKINNED_MESH_BINDING_SKINNED_TANGENT
#define NWB_SKINNED_MESH_BINDING_SKINNED_TANGENT 5
#undef NWB_SKINNED_MESH_BINDING_MESHLET_DESC
#define NWB_SKINNED_MESH_BINDING_MESHLET_DESC 6
#undef NWB_SKINNED_MESH_BINDING_POSITION_REF_DELTAS
#define NWB_SKINNED_MESH_BINDING_POSITION_REF_DELTAS 7
#undef NWB_SKINNED_MESH_BINDING_ATTRIBUTE_REF_DELTAS
#define NWB_SKINNED_MESH_BINDING_ATTRIBUTE_REF_DELTAS 8
#undef NWB_SKINNED_MESH_BINDING_ATTRIBUTE_SKINS
#define NWB_SKINNED_MESH_BINDING_ATTRIBUTE_SKINS 9
#undef NWB_SKINNED_MESH_BINDING_SKIN_INFLUENCES
#define NWB_SKINNED_MESH_BINDING_SKIN_INFLUENCES 10
#undef NWB_SKINNED_MESH_BINDING_JOINT_PALETTE
#define NWB_SKINNED_MESH_BINDING_JOINT_PALETTE 11

#undef NWB_SKINNED_MESH_BOUNDS_BINDING_POSITIONS
#define NWB_SKINNED_MESH_BOUNDS_BINDING_POSITIONS 0
#undef NWB_SKINNED_MESH_BOUNDS_BINDING_MESHLET_DESC
#define NWB_SKINNED_MESH_BOUNDS_BINDING_MESHLET_DESC 1
#undef NWB_SKINNED_MESH_BOUNDS_BINDING_POSITION_REF_DELTAS
#define NWB_SKINNED_MESH_BOUNDS_BINDING_POSITION_REF_DELTAS 2
#undef NWB_SKINNED_MESH_BOUNDS_BINDING_LOCAL_VERTEX_REFS
#define NWB_SKINNED_MESH_BOUNDS_BINDING_LOCAL_VERTEX_REFS 3
#undef NWB_SKINNED_MESH_BOUNDS_BINDING_PRIMITIVE_INDICES
#define NWB_SKINNED_MESH_BOUNDS_BINDING_PRIMITIVE_INDICES 4
#undef NWB_SKINNED_MESH_BOUNDS_BINDING_DYNAMIC_BOUNDS
#define NWB_SKINNED_MESH_BOUNDS_BINDING_DYNAMIC_BOUNDS 5


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


#endif
#undef NWB_SKINNED_MESH_BINDING_SLOTS_H

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

