// limztudio@gmail.com
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////



#ifndef NWB_GRAPHICS_SKINNED_MESH_CONSTANTS_H
#define NWB_GRAPHICS_SKINNED_MESH_CONSTANTS_H


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


#undef NWB_SKINNED_MESH_SKINNING_MODE_LINEAR_BLEND
#define NWB_SKINNED_MESH_SKINNING_MODE_LINEAR_BLEND 0u
#undef NWB_SKINNED_MESH_SKINNING_MODE_DUAL_QUATERNION
#define NWB_SKINNED_MESH_SKINNING_MODE_DUAL_QUATERNION 1u

#undef NWB_SKINNED_MESH_GROUP_SIZE_X
#define NWB_SKINNED_MESH_GROUP_SIZE_X 64
#undef NWB_SKINNED_MESH_BOUNDS_GROUP_SIZE_X
#define NWB_SKINNED_MESH_BOUNDS_GROUP_SIZE_X 128
#undef NWB_SKINNED_MESH_EPSILON
#define NWB_SKINNED_MESH_EPSILON 0.000001
#undef NWB_SKINNED_MESH_SKIN_INFLUENCE_FLOAT_COUNT
#define NWB_SKINNED_MESH_SKIN_INFLUENCE_FLOAT_COUNT 8u
#undef NWB_SKINNED_MESH_JOINT_MATRIX_FLOAT_COUNT
#define NWB_SKINNED_MESH_JOINT_MATRIX_FLOAT_COUNT 16u

#undef NWB_SKINNED_MESH_PUSH_MESHLET_COUNT
#define NWB_SKINNED_MESH_PUSH_MESHLET_COUNT 0u
#undef NWB_SKINNED_MESH_PUSH_SKIN_COUNT
#define NWB_SKINNED_MESH_PUSH_SKIN_COUNT 1u
#undef NWB_SKINNED_MESH_PUSH_JOINT_COUNT
#define NWB_SKINNED_MESH_PUSH_JOINT_COUNT 2u
#undef NWB_SKINNED_MESH_PUSH_SKINNING_MODE
#define NWB_SKINNED_MESH_PUSH_SKINNING_MODE 3u
#undef NWB_SKINNED_MESH_PUSH_ATTRIBUTE_COUNT
#define NWB_SKINNED_MESH_PUSH_ATTRIBUTE_COUNT 4u
#undef NWB_SKINNED_MESH_PUSH_CONSTANT_BYTE_SIZE
#define NWB_SKINNED_MESH_PUSH_CONSTANT_BYTE_SIZE 32u

#undef NWB_SKINNED_MESH_BOUNDS_PUSH_MESHLET_COUNT
#define NWB_SKINNED_MESH_BOUNDS_PUSH_MESHLET_COUNT 0u
#undef NWB_SKINNED_MESH_BOUNDS_PUSH_CONSTANT_BYTE_SIZE
#define NWB_SKINNED_MESH_BOUNDS_PUSH_CONSTANT_BYTE_SIZE 16u


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


#endif
#undef NWB_GRAPHICS_SKINNED_MESH_CONSTANTS_H

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

