// limztudio@gmail.com
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////



#ifndef NWB_DEFERRED_BINDING_SLOTS_H
#define NWB_DEFERRED_BINDING_SLOTS_H


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


#undef NWB_DEFERRED_LIGHTING_SET
#define NWB_DEFERRED_LIGHTING_SET 0
#undef NWB_DEFERRED_COMPOSITE_SET
#define NWB_DEFERRED_COMPOSITE_SET 0

#undef NWB_DEFERRED_LIGHTING_BINDING_GBUFFER_BASE_COLOR
#define NWB_DEFERRED_LIGHTING_BINDING_GBUFFER_BASE_COLOR 0
#undef NWB_DEFERRED_LIGHTING_BINDING_GBUFFER_NORMAL
#define NWB_DEFERRED_LIGHTING_BINDING_GBUFFER_NORMAL 1
#undef NWB_DEFERRED_LIGHTING_BINDING_GBUFFER_WORLD_POSITION
#define NWB_DEFERRED_LIGHTING_BINDING_GBUFFER_WORLD_POSITION 2
#undef NWB_DEFERRED_LIGHTING_BINDING_GBUFFER_DEPTH
#define NWB_DEFERRED_LIGHTING_BINDING_GBUFFER_DEPTH 3
#undef NWB_DEFERRED_LIGHTING_BINDING_SAMPLER
#define NWB_DEFERRED_LIGHTING_BINDING_SAMPLER 4

#undef NWB_DEFERRED_COMPOSITE_BINDING_OPAQUE_COLOR
#define NWB_DEFERRED_COMPOSITE_BINDING_OPAQUE_COLOR 0
#undef NWB_DEFERRED_COMPOSITE_BINDING_AVBOIT_ACCUM_COLOR
#define NWB_DEFERRED_COMPOSITE_BINDING_AVBOIT_ACCUM_COLOR 1
#undef NWB_DEFERRED_COMPOSITE_BINDING_AVBOIT_ACCUM_EXTINCTION
#define NWB_DEFERRED_COMPOSITE_BINDING_AVBOIT_ACCUM_EXTINCTION 2
#undef NWB_DEFERRED_COMPOSITE_BINDING_SAMPLER
#define NWB_DEFERRED_COMPOSITE_BINDING_SAMPLER 3

#undef NWB_DEFERRED_FULLSCREEN_UV_LOCATION
#define NWB_DEFERRED_FULLSCREEN_UV_LOCATION 0
#undef NWB_DEFERRED_COLOR_TARGET_LOCATION
#define NWB_DEFERRED_COLOR_TARGET_LOCATION 0


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


#endif
#undef NWB_DEFERRED_BINDING_SLOTS_H

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

