include_guard(GLOBAL)

macro(nwb_require_supported_architecture)
    if(NOT CMAKE_SIZEOF_VOID_P EQUAL 8)
        message(FATAL_ERROR "NWBLot supports 64-bit x64 and ARM64 targets only.")
    endif()

    if(NOT DEFINED NWB_TARGET_ARCH OR NWB_TARGET_ARCH STREQUAL "")
        set(_nwb_requested_arch "${CMAKE_SYSTEM_PROCESSOR}")
    else()
        set(_nwb_requested_arch "${NWB_TARGET_ARCH}")
    endif()
    string(TOLOWER "${_nwb_requested_arch}" _nwb_requested_arch)

    if(_nwb_requested_arch MATCHES "^(x64|amd64|x86_64|x86-64)$")
        set(_nwb_resolved_arch "x64")
    elseif(_nwb_requested_arch MATCHES "^(arm64|aarch64)$")
        set(_nwb_resolved_arch "arm64")
    else()
        message(FATAL_ERROR
            "Unsupported NWB_TARGET_ARCH '${_nwb_requested_arch}'. Expected x64 or arm64."
        )
    endif()

    set(NWB_TARGET_ARCH "${_nwb_resolved_arch}" CACHE STRING "NWBLot target architecture" FORCE)
    set_property(CACHE NWB_TARGET_ARCH PROPERTY STRINGS x64 arm64)
    set(NWB_OUTPUT_ARCH "${_nwb_resolved_arch}")
    unset(_nwb_requested_arch)
    unset(_nwb_resolved_arch)
endmacro()

macro(nwb_resolve_output_domain)
    if(DEFINED NWB_OUTPUT_DOMAIN AND NOT NWB_OUTPUT_DOMAIN STREQUAL "")
        set(_nwb_output_domain "${NWB_OUTPUT_DOMAIN}")
    else()
        get_filename_component(_nwb_output_domain "${CMAKE_BINARY_DIR}" NAME)
        if(_nwb_output_domain STREQUAL "")
            set(_nwb_output_domain "default")
        endif()
    endif()

    string(TOLOWER "${CMAKE_SYSTEM_NAME}" NWB_OUTPUT_PLATFORM)
    set(NWB_OUTPUT_DOMAIN "${_nwb_output_domain}")
    if(NWB_OUTPUT_DOMAIN STREQUAL "engine")
        set(NWB_OUTPUT_ROOT "${PROJECT_SOURCE_DIR}/__exec/${NWB_OUTPUT_PLATFORM}/${NWB_OUTPUT_ARCH}")
    else()
        set(NWB_OUTPUT_ROOT "${PROJECT_SOURCE_DIR}/__exec/${NWB_OUTPUT_PLATFORM}/${NWB_OUTPUT_ARCH}/${NWB_OUTPUT_DOMAIN}")
    endif()
endmacro()

macro(nwb_configure_general_output)
    nwb_resolve_output_domain()

    foreach(_type RUNTIME LIBRARY ARCHIVE)
        foreach(_cfg IN LISTS NWB_BUILD_CONFIGURATIONS)
            string(TOUPPER "${_cfg}" _cfg_upper)
            set(CMAKE_${_type}_OUTPUT_DIRECTORY_${_cfg_upper} "${NWB_OUTPUT_ROOT}/${_cfg}")
        endforeach()
    endforeach()
endmacro()
