include_guard(GLOBAL)

macro(nwb_require_x64)
    if(NOT CMAKE_SIZEOF_VOID_P EQUAL 8)
        message(FATAL_ERROR "NWBLot currently supports x64/64-bit builds only.")
    endif()

    set(NWB_OUTPUT_ARCH "x64")
endmacro()

macro(nwb_resolve_output_domain)
    if(DEFINED NWB_OUTPUT_DOMAIN AND NOT NWB_OUTPUT_DOMAIN STREQUAL "")
        set(_nwb_output_domain "${NWB_OUTPUT_DOMAIN}")
    else()
        get_filename_component(_nwb_output_domain "${CMAKE_BINARY_DIR}" NAME)
        if(_nwb_output_domain STREQUAL "")
            set(_nwb_output_domain "default")
        endif()
    endif()

    string(TOLOWER "${CMAKE_SYSTEM_NAME}" NWB_OUTPUT_PLATFORM)
    set(NWB_OUTPUT_DOMAIN "${_nwb_output_domain}")
    set(NWB_OUTPUT_ROOT "${PROJECT_SOURCE_DIR}/__exec/${NWB_OUTPUT_PLATFORM}/${NWB_OUTPUT_ARCH}/${NWB_OUTPUT_DOMAIN}")
endmacro()

macro(nwb_configure_general_output)
    nwb_resolve_output_domain()

    foreach(_type RUNTIME LIBRARY ARCHIVE)
        foreach(_cfg dbg opt fin)
            string(TOUPPER "${_cfg}" _cfg_upper)
            set(CMAKE_${_type}_OUTPUT_DIRECTORY_${_cfg_upper} "${NWB_OUTPUT_ROOT}/${_cfg}")
        endforeach()
    endforeach()
endmacro()
