include_guard(GLOBAL)

function(nwb_apply_simd_avx2 target)
    if(NWB_TARGET_ARCH STREQUAL "x64")
        if(NWB_COMPILER_FRONTEND_MSVC)
            target_compile_options(${target} PRIVATE /arch:AVX2)
        else()
            target_compile_options(${target} PRIVATE -mavx2 -mfma -mf16c -msse4.2)
        endif()
    endif()
endfunction()
